In [1]:
import pandas as pd
import numpy as np
import re
import html

from urllib.parse import unquote, urlparse

In [2]:
df=pd.read_csv('csic_database.csv')

In [3]:
df.head(5)

,Unnamed: 0,Method,User-Agent,Pragma,Cache-Control,Accept,Accept-encoding,Accept-charset,language,host,cookie,content-type,connection,lenght,content,classification,URL
0,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...

In [4]:
df.describe()

       classification
count    61065.000000
mean         0.410464
std          0.491922
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          1.000000

In [5]:
print(df.shape)

(61065, 17)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61065 entries, 0 to 61064
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       61065 non-null  object
 1   Method           61065 non-null  object
 2   User-Agent       61065 non-null  object
 3   Pragma           61065 non-null  object
 4   Cache-Control    61065 non-null  object
 5   Accept           60668 non-null  object
 6   Accept-encoding  61065 non-null  object
 7   Accept-charset   61065 non-null  object
 8   language         61065 non-null  object
 9   host             61065 non-null  object
 10  cookie           61065 non-null  object
 11  content-type     17977 non-null  object
 12  connection       61065 non-null  object
 13  lenght           17977 non-null  object
 14  content          17977 non-null  object
 15  classification   61065 non-null  int64
 16  URL              61065 non-null  object
dtypes: int64(1), object(16)
memory usage: 7.9+ MB

In [7]:
print(df.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['Unnamed: 0', 'Method', 'User-Agent', 'Pragma', 'Cache-Control',
       'Accept', 'Accept-encoding', 'Accept-charset', 'language', 'host',
       'cookie', 'content-type', 'connection', 'lenght', 'content',
       'classification', 'URL'],
      dtype='object')>

In [8]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

In [9]:
df.head()

,unnamed:_0,method,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,host,cookie,content_type,connection,lenght,content,classification,url
0,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...

In [10]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [11]:
print(df.columns.tolist())

['unnamed:_0', 'method', 'user_agent', 'pragma', 'cache_control', 'accept', 'accept_encoding', 'accept_charset', 'language', 'host', 'cookie', 'content_type', 'connection', 'lenght', 'content', 'classification', 'url']

In [12]:
if "Unnamed: 0" in df.columns:
    print(df["Unnamed: 0"].head(10))
    print(df["Unnamed: 0"].tail(10))
else:
    print("'Unnamed: 0' column does not exist")

'Unnamed: 0' column does not exist

In [13]:
print("Columns in df:")
print(df.columns.tolist())

print("\nShape:")
print(df.shape)

print("\nFirst 5 rows:")
display(df.head())

Columns in df:
['unnamed:_0', 'method', 'user_agent', 'pragma', 'cache_control', 'accept', 'accept_encoding', 'accept_charset', 'language', 'host', 'cookie', 'content_type', 'connection', 'lenght', 'content', 'classification', 'url']

Shape:
(61065, 17)

First 5 rows:

,unnamed:_0,method,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,host,cookie,content_type,connection,lenght,content,classification,url
0,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...

In [14]:
df.columns = df.columns.astype(str).str.strip()

print(df.columns.tolist())

['unnamed:_0', 'method', 'user_agent', 'pragma', 'cache_control', 'accept', 'accept_encoding', 'accept_charset', 'language', 'host', 'cookie', 'content_type', 'connection', 'lenght', 'content', 'classification', 'url']

In [15]:
if "Method" in df.columns:
    print(df["Method"].value_counts(dropna=False))
else:
    print("Method column NOT FOUND")

Method column NOT FOUND

In [16]:
method_col = [col for col in df.columns 
              if str(col).strip().lower() == "method"]

print(method_col)

['method']

In [17]:
print(df[method_col[0]].value_counts(dropna=False))

method
GET     43088
POST    17580
PUT       397
Name: count, dtype: int64

In [18]:
print(df["classification"].value_counts())

classification
0    36000
1    25065
Name: count, dtype: int64

In [19]:
print(
    df["classification"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

classification
0    58.95
1    41.05
Name: proportion, dtype: float64

In [20]:
# 0 or 1 ko compare karne ke liye classification column ka use karenge. 0 ka matlab hai normal traffic aur 1 ka matlab hai attack traffic.
print("Available columns:")
print(df.columns.tolist())

print("\nCLASSIFICATION 0:")
display(
    df[df["classification"] == 0].head(10)
)

print("\nCLASSIFICATION 1:")
display(
    df[df["classification"] == 1].head(10)
)

Available columns:
['unnamed:_0', 'method', 'user_agent', 'pragma', 'cache_control', 'accept', 'accept_encoding', 'accept_charset', 'language', 'host', 'cookie', 'content_type', 'connection', 'lenght', 'content', 'classification', 'url']

CLASSIFICATION 0:

,unnamed:_0,method,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,host,cookie,content_type,connection,lenght,content,classification,url
0,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...
5,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=5254A7A7C7F0E74D699E6A9C9487795A,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/caracter...
6,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=417DBC69B2F909CCD574CFC69F56779F,application/x-www-form-urlencoded,Connection: close,Content-Length: 4,id=2,0,http://localhost:8080/tienda1/publico/caracter...
7,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=42B53DB3F82E67BBB24E57E9CDC8E008,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/carrito....
8,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=A651CE9798E1B71FCA9D9B2159432A22,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/entrar.j...
9,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=EE6A06EE8174FC2B05432AA5A0FCE998,application/x-www-form-urlencoded,Connection: close,Content-Length: 33,errorMsg=Credenciales+incorrectas,0,http://localhost:8080/tienda1/publico/entrar.j...

CLASSIFICATION 1:

,unnamed:_0,method,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,host,cookie,content_type,connection,lenght,content,classification,url
36000,Anomalous,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=B92A8B48B9008CD29F622A994E0F650D,NaN,close,NaN,NaN,1,http://localhost:8080/tienda1/publico/anadir.j...
36001,Anomalous,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=AE29AEEBDE479D5E1A18B4108C8E3CE0,application/x-www-form-urlencoded,Connection: close,Content-Length: 146,id=2&nombre=Jam%F3n+Ib%E9rico&precio=85&cantid...,1,http://localhost:8080/tienda1/publico/anadir.j...
36002,Anomalous,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=F563B5262843F12ECAE41815ABDEEA54,NaN,close,NaN,NaN,1,http://localhost:8080/tienda1/publico/anadir.j...
36003,Anomalous,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=3B654D6DF7F1466EE80D7F756B00E5D1,application/x-www-form-urlencoded,Connection: close,Content-Length: 77,id=2%2F&nombre=Jam%F3n+Ib%E9rico&precio=85&can...,1,http://localhost:8080/tienda1/publico/anadir.j...
36004,Anomalous,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=51A7470173188BBB993947F2283059E4,NaN,close,NaN,NaN,1,http://localhost:8080/asf-logo-wide.gif~ HTTP/1.1
36005,Anomalous,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=AC0EEEDD09663CB36C67DD1B787B0CF5,NaN,close,NaN,NaN,1,http://localhost:8080/tienda1/publico/autentic...
36006,Anomalous,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=D6037A58019A61C4E5745B952029D61F,application/x-www-form-urlencoded,Connection: close,Content-Length: 118,modo=entrar&login=bob%40%3CSCRipt%3Ealert%28Pa...,1,http://localhost:8080/tienda1/publico/autentic...
36007,Anomalous,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=0FCF23BE3D0EB007F5289208CE069EAA,NaN,close,NaN,NaN,1,http://localhost:8080/tienda1/publico/autentic...
36008,Anomalous,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8AF6B635AEBCD053B136669662597271,application/x-www-form-urlencoded,Connection: close,Content-Length: 69,modo=entrar&login=grimshaw&pwd=G%2F%2FlAc%2CIA...,1,http://localhost:8080/tienda1/publico/autentic...
36009,Anomalous,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=09BF818C8B6E9EFE9DF5F28745D5948B,NaN,close,NaN,NaN,1,http://localhost:8080/tienda1/publico/autentic...

In [21]:
df.head(5)

,unnamed:_0,method,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,host,cookie,content_type,connection,lenght,content,classification,url
0,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...

In [22]:
print("Total URLs:", df["url"].shape[0])
print("Unique URLs:", df["url"].nunique())

Total URLs: 61065
Unique URLs: 13498

In [23]:
print(df["url"].head(20).to_string(index=False))

  http://localhost:8080/tienda1/index.jsp HTTP/1.1
http://localhost:8080/tienda1/publico/anadir.js...
http://localhost:8080/tienda1/publico/anadir.js...
http://localhost:8080/tienda1/publico/autentica...
http://localhost:8080/tienda1/publico/autentica...
http://localhost:8080/tienda1/publico/caracteri...
http://localhost:8080/tienda1/publico/caracteri...
http://localhost:8080/tienda1/publico/carrito.j...
http://localhost:8080/tienda1/publico/entrar.js...
http://localhost:8080/tienda1/publico/entrar.js...
http://localhost:8080/tienda1/publico/miembros....
http://localhost:8080/tienda1/publico/pagar.jsp...
http://localhost:8080/tienda1/publico/pagar.jsp...
http://localhost:8080/tienda1/publico/productos...
http://localhost:8080/tienda1/publico/registro....
http://localhost:8080/tienda1/publico/registro....
http://localhost:8080/tienda1/publico/vaciar.js...
http://localhost:8080/tienda1/publico/vaciar.js...
http://localhost:8080/tienda1/global/creditos.j...
http://localhost:8080/tienda1/global/menum.jsp ...

In [24]:

# 1. Preserve original URL
df["url_raw"] = df["url"].copy()

# 2. Separate URL and HTTP version
def split_url_http(value):
    value = str(value).strip()

    match = re.match(
        r"^(.*?)(?:\s+)(HTTP/\d(?:\.\d)?)$",
        value
    )

    if match:
        return pd.Series({
            "url": match.group(1),
            "http_version": match.group(2)
        })

    return pd.Series({
        "url": value,
        "http_version": None
    })

df[["url", "http_version"]] = (
    df["url_raw"].apply(split_url_http)
)

# 3. Inspect
display(
    df[
        ["url_raw", "url", "http_version"]
    ].head(20)
)

# 4. Check HTTP versions
print("\nHTTP Version Distribution:")
print(df["http_version"].value_counts(dropna=False))

,url_raw,url,http_version
0,http://localhost:8080/tienda1/index.jsp HTTP/1.1,http://localhost:8080/tienda1/index.jsp,HTTP/1.1
1,http://localhost:8080/tienda1/publico/anadir.j...,http://localhost:8080/tienda1/publico/anadir.j...,HTTP/1.1
2,http://localhost:8080/tienda1/publico/anadir.j...,http://localhost:8080/tienda1/publico/anadir.jsp,HTTP/1.1
3,http://localhost:8080/tienda1/publico/autentic...,http://localhost:8080/tienda1/publico/autentic...,HTTP/1.1
4,http://localhost:8080/tienda1/publico/autentic...,http://localhost:8080/tienda1/publico/autentic...,HTTP/1.1
5,http://localhost:8080/tienda1/publico/caracter...,http://localhost:8080/tienda1/publico/caracter...,HTTP/1.1
6,http://localhost:8080/tienda1/publico/caracter...,http://localhost:8080/tienda1/publico/caracter...,HTTP/1.1
7,http://localhost:8080/tienda1/publico/carrito....,http://localhost:8080/tienda1/publico/carrito.jsp,HTTP/1.1
8,http://localhost:8080/tienda1/publico/entrar.j...,http://localhost:8080/tienda1/publico/entrar.j...,HTTP/1.1
9,http://localhost:8080/tienda1/publico/entrar.j...,http://localhost:8080/tienda1/publico/entrar.jsp,HTTP/1.1
10,http://localhost:8080/tienda1/publico/miembros...,http://localhost:8080/tienda1/publico/miembros...,HTTP/1.1
11,http://localhost:8080/tienda1/publico/pagar.js...,http://localhost:8080/tienda1/publico/pagar.js...,HTTP/1.1
12,http://localhost:8080/tienda1/publico/pagar.js...,http://localhost:8080/tienda1/publico/pagar.jsp,HTTP/1.1
13,http://localhost:8080/tienda1/publico/producto...,http://localhost:8080/tienda1/publico/producto...,HTTP/1.1
14,http://localhost:8080/tienda1/publico/registro...,http://localhost:8080/tienda1/publico/registro...,HTTP/1.1
15,http://localhost:8080/tienda1/publico/registro...,http://localhost:8080/tienda1/publico/registro...,HTTP/1.1
16,http://localhost:8080/tienda1/publico/vaciar.j...,http://localhost:8080/tienda1/publico/vaciar.j...,HTTP/1.1
17,http://localhost:8080/tienda1/publico/vaciar.j...,http://localhost:8080/tienda1/publico/vaciar.jsp,HTTP/1.1
18,http://localhost:8080/tienda1/global/creditos....,http://localhost:8080/tienda1/global/creditos.jsp,HTTP/1.1
19,http://localhost:8080/tienda1/global/menum.jsp...,http://localhost:8080/tienda1/global/menum.jsp,HTTP/1.1

HTTP Version Distribution:
http_version
HTTP/1.1    61065
Name: count, dtype: int64

In [25]:
for i in range(10):
    print(repr(df["url"].iloc[i]))

'http://localhost:8080/tienda1/index.jsp'
'http://localhost:8080/tienda1/publico/anadir.jsp?id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A%F1adir+al+carrito'
'http://localhost:8080/tienda1/publico/anadir.jsp'
'http://localhost:8080/tienda1/publico/autenticar.jsp?modo=entrar&login=choong&pwd=d1se3ci%F3n&remember=off&B1=Entrar'
'http://localhost:8080/tienda1/publico/autenticar.jsp'
'http://localhost:8080/tienda1/publico/caracteristicas.jsp?id=2'
'http://localhost:8080/tienda1/publico/caracteristicas.jsp'
'http://localhost:8080/tienda1/publico/carrito.jsp'
'http://localhost:8080/tienda1/publico/entrar.jsp?errorMsg=Credenciales+incorrectas'
'http://localhost:8080/tienda1/publico/entrar.jsp'

In [26]:
print(
    df["url"]
    .astype(str)
    .str.contains("HTTP/1.1", regex=False)
    .sum()
)

0

In [27]:
print(
    df["url"]
    .astype(str)
    .str.contains("HTTP/", regex=False)
    .sum()
)

0

In [28]:
df["http_version"]

0        HTTP/1.1
1        HTTP/1.1
2        HTTP/1.1
3        HTTP/1.1
4        HTTP/1.1
           ...
61060    HTTP/1.1
61061    HTTP/1.1
61062    HTTP/1.1
61063    HTTP/1.1
61064    HTTP/1.1
Name: http_version, Length: 61065, dtype: object

In [29]:
df.drop(columns=["http_version"], inplace=True)

In [30]:
print(repr(df["url"].iloc[1]))

'http://localhost:8080/tienda1/publico/anadir.jsp?id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A%F1adir+al+carrito'

In [31]:
#url parsing kar raha hu iss step
from urllib.parse import urlparse
import pandas as pd

def parse_url(url):
    try:
        parsed = urlparse(str(url).strip())

        # Safely extract port
        try:
            port = parsed.port
        except ValueError:
            port = None

        return pd.Series({
            "scheme": parsed.scheme,
            "url_host": parsed.hostname,
            "port": port,
            "path": parsed.path,
            "query": parsed.query
        })

    except Exception:
        return pd.Series({
            "scheme": None,
            "url_host": None,
            "port": None,
            "path": None,
            "query": None
        })


df[["scheme", "url_host", "port", "path", "query"]] = (
    df["url"].apply(parse_url)
)

In [32]:
display(
    df[
        ["url", "scheme", "url_host", "port", "path", "query"]
    ].head(10)
)

,url,scheme,url_host,port,path,query
0,http://localhost:8080/tienda1/index.jsp,http,localhost,8080.0,/tienda1/index.jsp,
1,http://localhost:8080/tienda1/publico/anadir.j...,http,localhost,8080.0,/tienda1/publico/anadir.jsp,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...
2,http://localhost:8080/tienda1/publico/anadir.jsp,http,localhost,8080.0,/tienda1/publico/anadir.jsp,
3,http://localhost:8080/tienda1/publico/autentic...,http,localhost,8080.0,/tienda1/publico/autenticar.jsp,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...
4,http://localhost:8080/tienda1/publico/autentic...,http,localhost,8080.0,/tienda1/publico/autenticar.jsp,
5,http://localhost:8080/tienda1/publico/caracter...,http,localhost,8080.0,/tienda1/publico/caracteristicas.jsp,id=2
6,http://localhost:8080/tienda1/publico/caracter...,http,localhost,8080.0,/tienda1/publico/caracteristicas.jsp,
7,http://localhost:8080/tienda1/publico/carrito.jsp,http,localhost,8080.0,/tienda1/publico/carrito.jsp,
8,http://localhost:8080/tienda1/publico/entrar.j...,http,localhost,8080.0,/tienda1/publico/entrar.jsp,errorMsg=Credenciales+incorrectas
9,http://localhost:8080/tienda1/publico/entrar.jsp,http,localhost,8080.0,/tienda1/publico/entrar.jsp,

In [33]:
print(repr(df["url"].iloc[0]))
print(repr(df["url"].iloc[1]))
print(
    df["url"].astype(str)
    .str.contains("HTTP/", regex=False)
    .sum()
)

'http://localhost:8080/tienda1/index.jsp'
'http://localhost:8080/tienda1/publico/anadir.jsp?id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A%F1adir+al+carrito'
0

In [34]:
def get_parameter_count(query):
    try:
        return len(parse_qs(str(query)))
    except:
        return 0

df["parameter_count"] = df["query"].apply(get_parameter_count)

In [35]:
print(df["parameter_count"].describe())

count    61065.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: parameter_count, dtype: float64

In [36]:
df["url_length"] = df["url"].astype(str).str.len()

In [37]:
print(df["url_length"].describe())

count    61065.000000
mean        81.325358
std         75.547066
min         22.000000
25%         48.000000
50%         50.000000
75%         68.000000
max        886.000000
Name: url_length, dtype: float64

In [38]:
df["path_length"] = df["path"].astype(str).str.len()

In [39]:
df["query_length"] = df["query"].astype(str).str.len()

In [40]:
from urllib.parse import unquote

df["url_decoded"] = (
    df["url_raw"]
    .astype(str)
    .apply(unquote)
)

In [41]:
display(
    df[
        ["url_raw", "url_decoded"]
    ].head(10)
)

,url_raw,url_decoded
0,http://localhost:8080/tienda1/index.jsp HTTP/1.1,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,http://localhost:8080/tienda1/publico/anadir.j...,http://localhost:8080/tienda1/publico/anadir.j...
2,http://localhost:8080/tienda1/publico/anadir.j...,http://localhost:8080/tienda1/publico/anadir.j...
3,http://localhost:8080/tienda1/publico/autentic...,http://localhost:8080/tienda1/publico/autentic...
4,http://localhost:8080/tienda1/publico/autentic...,http://localhost:8080/tienda1/publico/autentic...
5,http://localhost:8080/tienda1/publico/caracter...,http://localhost:8080/tienda1/publico/caracter...
6,http://localhost:8080/tienda1/publico/caracter...,http://localhost:8080/tienda1/publico/caracter...
7,http://localhost:8080/tienda1/publico/carrito....,http://localhost:8080/tienda1/publico/carrito....
8,http://localhost:8080/tienda1/publico/entrar.j...,http://localhost:8080/tienda1/publico/entrar.j...
9,http://localhost:8080/tienda1/publico/entrar.j...,http://localhost:8080/tienda1/publico/entrar.j...

In [42]:
df["query_decoded"] = (
    df["query"]
    .fillna("")
    .astype(str)
    .apply(unquote)
)

In [43]:
special_chars = r"""'"><;"""

In [44]:
df["special_char_count"] = (
    df["url_decoded"]
    .astype(str)
    .apply(lambda x: sum(char in special_chars for char in x))
)

In [45]:
print(df["special_char_count"].describe())

count    61065.000000
mean         0.168329
std          1.059654
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         15.000000
Name: special_char_count, dtype: float64

In [46]:
df["encoding_count"] = (
    df["url_raw"]
    .astype(str)
    .str.count("%")
)

In [47]:
df["path_depth"] = (
    df["path"]
    .astype(str)
    .str.strip("/")
    .str.count("/")
    + 1
)

In [48]:
display(
    df[
        [
            "url_raw",
            "url_decoded",
            "scheme",
            "url_host",
            "port",
            "path",
            "query",
            "parameter_count",
            "url_length",
            "path_length",
            "query_length"
        ]
    ].head(10)
)

,url_raw,url_decoded,scheme,url_host,port,path,query,parameter_count,url_length,path_length,query_length
0,http://localhost:8080/tienda1/index.jsp HTTP/1.1,http://localhost:8080/tienda1/index.jsp HTTP/1.1,http,localhost,8080.0,/tienda1/index.jsp,,0,39,18,0
1,http://localhost:8080/tienda1/publico/anadir.j...,http://localhost:8080/tienda1/publico/anadir.j...,http,localhost,8080.0,/tienda1/publico/anadir.jsp,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,117,27,68
2,http://localhost:8080/tienda1/publico/anadir.j...,http://localhost:8080/tienda1/publico/anadir.j...,http,localhost,8080.0,/tienda1/publico/anadir.jsp,,0,48,27,0
3,http://localhost:8080/tienda1/publico/autentic...,http://localhost:8080/tienda1/publico/autentic...,http,localhost,8080.0,/tienda1/publico/autenticar.jsp,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,116,31,63
4,http://localhost:8080/tienda1/publico/autentic...,http://localhost:8080/tienda1/publico/autentic...,http,localhost,8080.0,/tienda1/publico/autenticar.jsp,,0,52,31,0
5,http://localhost:8080/tienda1/publico/caracter...,http://localhost:8080/tienda1/publico/caracter...,http,localhost,8080.0,/tienda1/publico/caracteristicas.jsp,id=2,0,62,36,4
6,http://localhost:8080/tienda1/publico/caracter...,http://localhost:8080/tienda1/publico/caracter...,http,localhost,8080.0,/tienda1/publico/caracteristicas.jsp,,0,57,36,0
7,http://localhost:8080/tienda1/publico/carrito....,http://localhost:8080/tienda1/publico/carrito....,http,localhost,8080.0,/tienda1/publico/carrito.jsp,,0,49,28,0
8,http://localhost:8080/tienda1/publico/entrar.j...,http://localhost:8080/tienda1/publico/entrar.j...,http,localhost,8080.0,/tienda1/publico/entrar.jsp,errorMsg=Credenciales+incorrectas,0,82,27,33
9,http://localhost:8080/tienda1/publico/entrar.j...,http://localhost:8080/tienda1/publico/entrar.j...,http,localhost,8080.0,/tienda1/publico/entrar.jsp,,0,48,27,0

In [49]:
from urllib.parse import parse_qs

In [50]:
def count_parameters(query):
    if pd.isna(query) or str(query).strip() == "":
        return 0
    
    return len(parse_qs(str(query), keep_blank_values=True))

In [51]:
df["parameter_count"] = df["query"].apply(count_parameters)

In [52]:
display(
    df[
        ["query", "parameter_count"]
    ].head(10)
)

                                               query  parameter_count
0                                                                   0
1  id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...                5
2                                                                   0
3  modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...                5
4                                                                   0
5                                               id=2                1
6                                                                   0
7                                                                   0
8                  errorMsg=Credenciales+incorrectas                1
9                                                                   0

In [53]:
print(repr(df["url_raw"].iloc[1]))
print(repr(df["url_decoded"].iloc[1]))

'http://localhost:8080/tienda1/publico/anadir.jsp?id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A%F1adir+al+carrito HTTP/1.1'
'http://localhost:8080/tienda1/publico/anadir.jsp?id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A�adir+al+carrito HTTP/1.1'

In [54]:
df["query_decoded"]=(
    df["query"]
    .fillna("")
    .astype(str)
    .apply(unquote)
)

In [55]:
print(df["query"].iloc[1])
print(df["query_decoded"].iloc[1])

id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A%F1adir+al+carrito
id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A�adir+al+carrito

In [56]:
sample_query=df["query"].iloc[1]
print(parse_qs(sample_query,keep_blank_values=True))

{'id': ['3'], 'nombre': ['Vino Rioja'], 'precio': ['100'], 'cantidad': ['55'], 'B1': ['A�adir al carrito']}

In [57]:
print(df["parameter_count"].describe())

count    61065.000000
mean         1.604372
std          3.589827
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max         13.000000
Name: parameter_count, dtype: float64

In [58]:
print(
    df.groupby("classification")["parameter_count"].describe()
)

                  count      mean       std  min  25%  50%  75%   max
classification
0               36000.0  1.166667  3.122542  0.0  0.0  0.0  0.0  13.0
1               25065.0  2.233034  4.089252  0.0  0.0  0.0  3.0  13.0

In [59]:
df["encoding_count"]=(
    df["url_raw"]
    .astype(str)
    .str.count("%")
)

In [60]:
print(df["encoding_count"].describe())

count    61065.000000
mean         0.937722
std          4.651172
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        114.000000
Name: encoding_count, dtype: float64

In [61]:
print(
    df.groupby("classification")["encoding_count"].describe()
)

                  count      mean       std  min  25%  50%  75%    max
classification
0               36000.0  0.265944  0.990859  0.0  0.0  0.0  0.0   12.0
1               25065.0  1.902573  7.051003  0.0  0.0  0.0  1.0  114.0

In [62]:


df["encoded_sequence_count"] = (
    df["url_raw"]
    .astype(str)
    .apply(
        lambda x: len(re.findall(r"%[0-9A-Fa-f]{2}", x))
    )
)

In [63]:
print(df["encoded_sequence_count"].describe())

count    61065.000000
mean         0.937722
std          4.651172
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        114.000000
Name: encoded_sequence_count, dtype: float64

In [64]:
print(
    df.groupby("classification")["encoded_sequence_count"].describe()
)

                  count      mean       std  min  25%  50%  75%    max
classification
0               36000.0  0.265944  0.990859  0.0  0.0  0.0  0.0   12.0
1               25065.0  1.902573  7.051003  0.0  0.0  0.0  1.0  114.0

In [65]:
special_chars="""'"><;%"""
df["special_char_count"]=(
    df["url_decoded"]
    .astype(str)
    .apply(
        lambda x: sum(char in special_chars for char in x)
    )
)

In [66]:
print(df["special_char_count"].describe())

count    61065.000000
mean         0.404241
std          4.015952
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        105.000000
Name: special_char_count, dtype: float64

In [67]:
print(
    df.groupby("classification")["special_char_count"].describe()
)

                  count      mean       std  min  25%  50%  75%    max
classification
0               36000.0  0.001472  0.040457  0.0  0.0  0.0  0.0    2.0
1               25065.0  0.982725  6.222756  0.0  0.0  0.0  0.0  105.0

In [68]:
df["slash_count"]=(
    df["path"]
    .astype(str)
    .str.count("/")
)

In [69]:
df["dot_count"]=(
    df["url_decoded"]
    .astype(str)
    .str.count(r"\.")
)

In [70]:
df["question_mark_count"]=(
    df["url_raw"]
    .astype(str)
    .str.count(r"\?")
)

In [71]:
df["question_mark_count"] = (
    df["url_raw"]
    .astype(str)
    .str.count(r"\?")
)

In [72]:
df["ampersand_count"] = (
    df["query"]
    .astype(str)
    .str.count("&")
)

In [73]:
print(
    df.groupby("classification")["encoding_count"].describe()
)

print(
    df.groupby("classification")["special_char_count"].describe()
)

                  count      mean       std  min  25%  50%  75%    max
classification
0               36000.0  0.265944  0.990859  0.0  0.0  0.0  0.0   12.0
1               25065.0  1.902573  7.051003  0.0  0.0  0.0  1.0  114.0
                  count      mean       std  min  25%  50%  75%    max
classification
0               36000.0  0.001472  0.040457  0.0  0.0  0.0  0.0    2.0
1               25065.0  0.982725  6.222756  0.0  0.0  0.0  0.0  105.0

In [74]:
def count_sql_keywords(text):
    text = str(text).lower()
    return len(
        re.findall(
            r"\b(select|union|insert|update|delete|drop|alter|create|exec|execute)\b",
            text
        )
    )

df["sql_keyword_count"] = (
    df["url_decoded"].apply(count_sql_keywords)
)

In [75]:
df["sql_special_count"]=(
    df["url_decoded"]
    .astype(str)
    .apply(
        lambda x: sum(
            c in "'\";=" for c in x
        )
    )
)

In [76]:
sql_comment_pattern = r"(--|/\*|\*/|#)"

df["sql_comment_count"] = (
    df["url_decoded"]
    .astype(str)
    .apply(
        lambda x: len(
            re.findall(
                sql_comment_pattern,
                x,
                flags=re.IGNORECASE
            )
        )
    )
)

In [77]:
sql_logic_pattern = r"\b(and|or)\b"

df["sql_logic_count"] = (
    df["url_decoded"]
    .astype(str)
    .apply(
        lambda x: len(
            re.findall(
                sql_logic_pattern,
                x,
                flags=re.IGNORECASE
            )
        )
    )
)

In [78]:
sql_features = [
    "sql_keyword_count",
    "sql_special_count",
    "sql_comment_count",
    "sql_logic_count"
]

print(
    df.groupby("classification")[sql_features]
      .mean()
)

                sql_keyword_count  sql_special_count  sql_comment_count  \
classification
0                        0.000056           1.168139           0.000000
1                        0.022142           2.612009           0.065749

                sql_logic_count
classification
0                      0.000167
1                      0.012368

In [79]:
print(
    df.groupby("classification")[sql_features]
      .max()
)

                sql_keyword_count  sql_special_count  sql_comment_count  \
classification
0                               1                 15                  0
1                               2                 28                  3

                sql_logic_count
classification
0                             1
1                             1

In [80]:
print(
    df[
        [
            "url_raw",
            "url_decoded",
            "sql_keyword_count",
            "sql_special_count",
            "sql_comment_count",
            "sql_logic_count",
            "classification"
        ]
    ].head(20).to_string()
)

                                                                                                                                                                                                                                                                                                 url_raw                                                                                                                                                                                                                                                                                 url_decoded  sql_keyword_count  sql_special_count  sql_comment_count  sql_logic_count  classification
0                                                                                                                                                                                                                                                       http://localhost:8080/tienda1/index.jsp HTTP/1.1                                                                                                                                                                                                                                            http://localhost:8080/tienda1/index.jsp HTTP/1.1                  0                  0                  0                0               0
1                                                                                                                                                                         http://localhost:8080/tienda1/publico/anadir.jsp?id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A%F1adir+al+carrito HTTP/1.1                                                                                                                                                                http://localhost:8080/tienda1/publico/anadir.jsp?id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A�adir+al+carrito HTTP/1.1                  0                  5                  0                0               0
2                                                                                                                                                                                                                                              http://localhost:8080/tienda1/publico/anadir.jsp HTTP/1.1                                                                                                                                                                                                                                   http://localhost:8080/tienda1/publico/anadir.jsp HTTP/1.1                  0                  0                  0                0               0
3                                                                                                                                                                          http://localhost:8080/tienda1/publico/autenticar.jsp?modo=entrar&login=choong&pwd=d1se3ci%F3n&remember=off&B1=Entrar HTTP/1.1                                                                                                                                                                 http://localhost:8080/tienda1/publico/autenticar.jsp?modo=entrar&login=choong&pwd=d1se3ci�n&remember=off&B1=Entrar HTTP/1.1                  0                  5                  0                0               0
4                                                                                                                                                                                                                                          http://localhost:8080/tienda1/publico/autenticar.jsp HTTP/1.1                                                                                                                                                                                                                               http://localhost:8080/tienda1/publico/autenticar.jsp HTTP/1.1                  0                  0                  0                0               0
5                                                                                                                                                                                                                                http://localhost:8080/tienda1/publico/caracteristicas.jsp?id=2 HTTP/1.1                                                                                                                                                                                                                     http://localhost:8080/tienda1/publico/caracteristicas.jsp?id=2 HTTP/1.1                  0                  1                  0                0               0
6                                                                                                                                                                                                                                     http://localhost:8080/tienda1/publico/caracteristicas.jsp HTTP/1.1                                                                                                                                                                                                                          http://localhost:8080/tienda1/publico/caracteristicas.jsp HTTP/1.1                  0                  0                  0                0               0
7                                                                                                                                                                                                                                             http://localhost:8080/tienda1/publico/carrito.jsp HTTP/1.1                                                                                                                                                                                                                                  http://localhost:8080/tienda1/publico/carrito.jsp HTTP/1.1                  0                  0                  0                0               0
8                                                                                                                                                                                                            http://localhost:8080/tienda1/publico/entrar.jsp?errorMsg=Credenciales+incorrectas HTTP/1.1                                                                                                                                                                                                 http://localhost:8080/tienda1/publico/entrar.jsp?errorMsg=Credenciales+incorrectas HTTP/1.1                  0                  1                  0                0               0
9                                                                                                                                                                                                                                              http://localhost:8080/tienda1/publico/entrar.jsp HTTP/1.1                                                                                                                                                                                                                                   http://localhost:8080/tienda1/publico/entrar.jsp HTTP/1.1                  0                  0                  0                0               0
10                                                                                                                                                                                                                                           http://localhost:8080/tienda1/publico/miembros.jsp HTTP/1.1                                                                                                                                                                                                                                 http://localhost:8080/tienda1/publico/miembros.jsp HTTP/1.1                  0                  0                  0                0               0
11                                                                                                                                                                                                  http://localhost:8080/tienda1/publico/pagar.jsp?modo=insertar&precio=2672&B1=Pasar+por+caja HTTP/1.1                                                                                                                                                                                        http://localhost:8080/tienda1/publico/pagar.jsp?modo=insertar&precio=2672&B1=Pasar+por+caja HTTP/1.1                  0                  3                  0                0               0
12                                                                                                                                                                                                                                              http://localhost:8080/tienda1/publico/pagar.jsp HTTP/1.1                                                                                                                                                                                                                                    http://localhost:8080/tienda1/publico/pagar.jsp HTTP/1.1                  0                  0                  0                0               0
13                                                                                                                                                                                                                                          http://localhost:8080/tienda1/publico/productos.jsp HTTP/1.1                                                                                                                                                                                                                                http://localhost:8080/tienda1/publico/productos.jsp HTTP/1.1                  0                  0                  0                0               0
14  http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=cen&password=40a5E&nombre=Nurit&apellidos=Ferrandez+Caba%F1as&email=tarpey%40bwds.ne&dni=17621392B&direccion=Calle+Clavel+30+11%3FB&ciudad=Tronch%F3n&cp=17463&provincia=C%E1ceres&ntc=1527409541807001&B1=Registrar HTTP/1.1  http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=cen&password=40a5E&nombre=Nurit&apellidos=Ferrandez+Caba�as&email=tarpey@bwds.ne&dni=17621392B&direccion=Calle+Clavel+30+11?B&ciudad=Tronch�n&cp=17463&provincia=C�ceres&ntc=1527409541807001&B1=Registrar HTTP/1.1                  0                 13                  0                0               0
15                                                                                                                                                                                                                                           http://localhost:8080/tienda1/publico/registro.jsp HTTP/1.1                                                                                                                                                                                                                                 http://localhost:8080/tienda1/publico/registro.jsp HTTP/1.1                  0                  0                  0                0               0
16                                                                                                                                                                                                                           http://localhost:8080/tienda1/publico/vaciar.jsp?B2=Vaciar+carrito HTTP/1.1                                                                                                                                                                                                                 http://localhost:8080/tienda1/publico/vaciar.jsp?B2=Vaciar+carrito HTTP/1.1                  0                  1                  0                0               0
17                                                                                                                                                                                                                                             http://localhost:8080/tienda1/publico/vaciar.jsp HTTP/1.1                                                                                                                                                                                                                                   http://localhost:8080/tienda1/publico/vaciar.jsp HTTP/1.1                  0                  0                  0                0               0
18                                                                                                                                                                                                                                            http://localhost:8080/tienda1/global/creditos.jsp HTTP/1.1                                                                                                                                                                                                                                  http://localhost:8080/tienda1/global/creditos.jsp HTTP/1.1                  0                  0                  0                0               0
19                                                                                                                                                                                                                                               http://localhost:8080/tienda1/global/menum.jsp HTTP/1.1                                                                                                                                                                                                                                     http://localhost:8080/tienda1/global/menum.jsp HTTP/1.1                  0                  0                  0                0               0

In [81]:
df["has_sql_keyword"] = (
    df["sql_keyword_count"] > 0
).astype(int)

In [82]:
df["has_sql_comment"] = (
    df["sql_comment_count"] > 0
).astype(int)

In [83]:
df["single_quote_count"] = (
    df["url_decoded"]
    .astype(str)
    .str.count("'")
)

df["double_quote_count"] = (
    df["url_decoded"]
    .astype(str)
    .str.count('"')
)

In [84]:
df["sql_operator_count"] = (
    df["url_decoded"]
    .astype(str)
    .apply(
        lambda x: sum(c in "=<>;" for c in x)
    )
)

In [85]:
df["has_encoding"] = (
    df["encoded_sequence_count"] > 0
).astype(int)

In [86]:
df["query_sql_keyword_count"] = (
    df["query_decoded"]
    .astype(str)
    .apply(count_sql_keywords)
)

In [87]:
print(
    pd.crosstab(
        df["has_sql_keyword"],
        df["classification"],
        normalize="columns"
    ) * 100
)

classification           0          1
has_sql_keyword
0                99.994444  98.192699
1                 0.005556   1.807301

In [88]:
print(
    pd.crosstab(
        df["has_sql_comment"],
        df["classification"],
        normalize="columns"
    ) * 100
)

classification       0          1
has_sql_comment
0                100.0  96.313585
1                  0.0   3.686415

In [89]:
features = [
    "url_length",
    "path_length",
    "query_length",
    "parameter_count",
    "encoded_sequence_count",
    "special_char_count",
    "sql_keyword_count",
    "sql_comment_count",
    "sql_logic_count"
]

summary = df.groupby("classification")[features].agg(
    ["mean", "median", "max"]
)

print(summary)

               url_length             path_length            query_length  \
                     mean median  max        mean median max         mean
classification
0               69.985944   49.5  358   28.416667   27.0  37    20.347056
1               97.611769   55.0  886   29.058169   28.0  66    47.133613

                           parameter_count  ... special_char_count  \
               median  max            mean  ...                max
classification                              ...
0                 0.0  307        1.166667  ...                  2
1                 0.0  836        2.233034  ...                105

               sql_keyword_count            sql_comment_count             \
                            mean median max              mean median max
classification
0                       0.000056    0.0   1          0.000000    0.0   0
1                       0.022142    0.0   2          0.065749    0.0   3

               sql_logic_count
                          mean median max
classification
0                     0.000167    0.0   1
1                     0.012368    0.0   1

[2 rows x 27 columns]

In [90]:
print(
    df.loc[
        df["special_char_count"] > 0,
        [
            "url_decoded",
            "special_char_count",
            "classification"
        ]
    ].head(30).to_string()
)

                                                                                                                                                                                                                                                                                                                                        url_decoded  special_char_count  classification
350                                        http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=maurie&password=0StroP5je0&nombre=Vlentina&apellidos=Fisas&email=marlaud_losee5@redesmilitantes.tf&dni=54430634F&direccion=Viseu+81+8?C&ciudad=Corbera+d'Ebre&cp=48210&provincia=Murcia&ntc=4713791605534130&B1=Registrar HTTP/1.1                   1               0
530                         http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=threader&password=dESCOlocaDO&nombre=Mallki&apellidos=Moreno+Undurraga&email=stevenin@ceramicasmi�o.mn&dni=70153244R&direccion=C/+Vapor,+148,+2?A&ciudad=Espluga+Calba,+L'&cp=03153&provincia=Palencia&ntc=5838987688567542&B1=Registrar HTTP/1.1                   1               0
1850                        http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=jean-yve&password=reTEjAdOR&nombre=Cancia&apellidos=O'Kinghtons+Camarena&email=olrich-shapiro1@nuriamartin.aw&dni=97060354D&direccion=Senda+Buen+Paso+S/N,+&ciudad=Luesia&cp=22390&provincia=Asturias&ntc=8267431025409914&B1=Registrar HTTP/1.1                   1               0
2390                   http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=doan7&password=mil�sima&nombre=Yaideem&apellidos=Penido+Maym'o&email=olaughlin@pinkplanetplasencia.uy&dni=37662577P&direccion=Avenida+San+Francisco+Javier,+5,+&ciudad=D�lar&cp=24324&provincia=Valladolid&ntc=2781714156257998&B1=Registrar HTTP/1.1                   1               0
2618                                     http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=pomeroy5&password=C5fRA98&nombre=Bonifacio&apellidos=Iranzo&email=wyle@designworld.us&dni=88356550A&direccion=C/+Ca+N'alzina,+80,+6-B&ciudad=Requena+de+Campos&cp=45110&provincia=Granada&ntc=8995996565558024&B1=Registrar HTTP/1.1                   1               0
3326                               http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=boisvert&password=ma27ta&nombre=Paladio&apellidos=D'Amico+Urrea&email=mcnear.trotta@lettere.ve&dni=11295198J&direccion=Robert+Graves,+101+&ciudad=Casillas+de+Flores&cp=50300&provincia=Madrid&ntc=1889610781907232&B1=Registrar HTTP/1.1                   1               0
3590                                http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=bekki&password=retinte&nombre=Harry&apellidos=Capella+Gorr�n&email=gunner@piaceredelivery.kw&dni=78532141K&direccion=Isabel+La+Catolica,+34+&ciudad=Ribera+d'Ondara&cp=08250&provincia=Ourense&ntc=7930754215612383&B1=Registrar HTTP/1.1                   1               0
4010                                  http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=rec&password=CuITADa&nombre=Nahir&apellidos=Espineta+Astorquiza&email=pager@cocheacoche.ws&dni=85673796S&direccion=Calle+Francisco+De+Leiva,+131,+&ciudad=Aldea,+L'&cp=44143&provincia=Le�n&ntc=7590918469472640&B1=Registrar HTTP/1.1                   1               0
4022            http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=tyler&password=Sa?BalErO&nombre=Didier&apellidos=Medel+Pujolriu&email=scely_prono@tobarisch.de&dni=63375335P&direccion=C/+Leopoldo+Alas+"clarin"+4,+6?B&ciudad=Sant+Lloren�+de+la+Muga&cp=46712&provincia=Palencia&ntc=1693717556836495&B1=Registrar HTTP/1.1                   2               0
4154                     http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=gates&password=fol0aDo&nombre=Genciano&apellidos=Cedo+Rosa's&email=kepinska@manuelpaloma.asia&dni=42808198T&direccion=Plza.+Santa+Maria+96+8?F&ciudad=Santa+Mar�a+de+la+Vega&cp=11639&provincia=La+Rioja&ntc=9122440516217949&B1=Registrar HTTP/1.1                   1               0
4202                                      http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=zarrabia&password=apo9�0ICO&nombre=Orion&apellidos=Linares+Queralto&email=nanook@cup-id.lu&dni=03199923W&direccion=Ronda+O'donnell,+106,+12?E&ciudad=Oj�s&cp=34419&provincia=Ciudad+Real&ntc=7298091091245974&B1=Registrar HTTP/1.1                   1               0
7766                      http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=rollie&password=p21urit56&nombre=Calistrato&apellidos=Correa+Cachopo&email=charlots7@e-b-s.bm&dni=63482988K&direccion=Calle+De+Circulacio+De+L'+Oest,+7+&ciudad=Osornillo&cp=05192&provincia=Guadalajara&ntc=2910118261122194&B1=Registrar HTTP/1.1                   1               0
7874                                                    http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=gittins&password=36lis8r&nombre=Katia&apellidos=Luque&email=clay@parcalia.ml&dni=92152955M&direccion=Font+D'en+Canyelles+21,+1-B&ciudad=Montseny&cp=02215&provincia=Toledo&ntc=8096640532589515&B1=Registrar HTTP/1.1                   1               0
8198                http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=vyza&password=DiSIPAr&nombre=Argelio&apellidos=Palau+Ustrell&email=greenhalgh@cafedeteatro.np&dni=81180031J&direccion=Cayetano+Polo+"polito"+90+2?A&ciudad=Santa+Mar�a+de+las+Hoyas&cp=28609&provincia=Badajoz&ntc=6449111559125327&B1=Registrar HTTP/1.1                   2               0
8870                        http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=zimmerer&password=gre�a&nombre=Adriel&apellidos=Llena+Astall�&email=olesen@ballobar.com.mr&dni=08071780E&direccion=Etorbidea+Atarrabiako+126,+5D&ciudad=Castell�+d'Emp�ries&cp=34492&provincia=Toledo&ntc=9301738715220065&B1=Registrar HTTP/1.1                   1               0
9734                      http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=zarlenga&password=anabaptismo&nombre=Bertoldo&apellidos=Lapaza+O'Neil&email=poncin@todobetis.mil&dni=58193627Q&direccion=Pasadizo+Fernandez+92+3-C&ciudad=Churriana+de+la+Vega&cp=06656&provincia=C�diz&ntc=8336103681905855&B1=Registrar HTTP/1.1                   1               0
9854                            http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=eva&password=animador!a&nombre=Alonso&apellidos=Chanes+Galvan&email=congregation@saludyfitness.pm&dni=08109487D&direccion=C/+Era+Val+D'aran+S/N,+7?E&ciudad=Benabarre&cp=43440&provincia=Salamanca&ntc=3685717385941815&B1=Registrar HTTP/1.1                   1               0
9998                                              http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=offers&password=orGullEZA&nombre=Hoel&apellidos=Estic�+O'Neil&email=bashan@lettere.pr&dni=49339665L&direccion=Cami�o+Da+Mina,+175,+&ciudad=Oroz-Betelu&cp=38690&provincia=Madrid&ntc=7714584958323378&B1=Registrar HTTP/1.1                   1               0
11726                                                       http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=kaneko&password=18l4et2ro&nombre=Ayen&apellidos=Anglaril&email=spradlin@pcvirus.dz&dni=65456048A&direccion=De+L'+Aliga+3,+&ciudad=Almadrones&cp=47110&provincia=M�laga&ntc=5861000706039696&B1=Registrar HTTP/1.1                   1               0
13046                                 http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=andries&password=bezante&nombre=Nicasio&apellidos=Suau+Feixa&email=hardwick@corjet.gh&dni=97084633T&direccion=Partida+Lliriet+D'en+Mig,+135,+10?A&ciudad=Villena&cp=46269&provincia=Navarra&ntc=4641290123831700&B1=Registrar HTTP/1.1                   1               0
13694  http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=triantap&password=arpe*nde&nombre=Alor&apellidos=De+Lagarza+Delacerda&email=felber@hiperespa�a.ps&dni=87179467Z&direccion=Calle+Poligon+Industrial+"el+Segre",+118+&ciudad=Vilanova+de+Arousa&cp=31790&provincia=Salamanca&ntc=3548348718435303&B1=Registrar HTTP/1.1                   2               0
14246                                            http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=mathieso&password=pesantez&nombre=Trinidad&apellidos=Mc'Morral+Obrist&email=jolley@decoaching.na&dni=50535908D&direccion=Azorin+35+1B&ciudad=Padiernos&cp=25613&provincia=Sevilla&ntc=8120300504791286&B1=Registrar HTTP/1.1                   1               0
14270                                        http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=gdowik2&password=29?em2ti3a&nombre=Grecia&apellidos=Ar�n+Pola&email=fravel@filtraciondehumos.sz&dni=48171319G&direccion=El+Vito,+90+&ciudad=Ampolla,+L'&cp=50100&provincia=Castell�n&ntc=1798713909636768&B1=Registrar HTTP/1.1                   1               0
14282                            http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=silvia&password=chuchazo&nombre=Antoliano&apellidos=Benajas+Rodr�guez&email=pearcy@b-sign.mz&dni=10560589R&direccion=C/+De+La+Riera+D'horta+105,+5?H&ciudad=Duesaig�es&cp=46725&provincia=Navarra&ntc=2409731978356224&B1=Registrar HTTP/1.1                   1               0
14378                                   http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=mariabel&password=c2645ido&nombre=Zelma&apellidos=Dotor+Fornell&email=celik-regan@turinga.sb&dni=95113653M&direccion=Carrer+Jaume+D'artes+78,+&ciudad=Osornillo&cp=10411&provincia=Burgos&ntc=3090147546194865&B1=Registrar HTTP/1.1                   1               0
15866                                   http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=bolly&password=pintarrajar&nombre=Gontr�n&apellidos=Tanquia+Jepus&email=mccollon@irmedia.ca&dni=38507707A&direccion=C/+Costa+i+Llobera+83+&ciudad=Corbera+d'Ebre&cp=18339&provincia=Madrid&ntc=3820743619643877&B1=Registrar HTTP/1.1                   1               0
16466                      http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=addons&password=14ab214c6�n&nombre=Karla&apellidos=Jauregui+Cortines&email=quartet@cabare.com.cs&dni=86800649Y&direccion=Paratge+Lila+30,+10?C&ciudad=Espluga+de+Francol�,+L'&cp=06380&provincia=�vila&ntc=9091453994786923&B1=Registrar HTTP/1.1                   1               0
18626                                 http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=soules&password=acomplexionada&nombre=Rigby&apellidos=Pascuet+Landivar&email=moskuna@sitcpla.ye&dni=45053569L&direccion=Duende,+138,+&ciudad=Guingueta+d'�neu,+La&cp=40170&provincia=Huesca&ntc=0029687955884916&B1=Registrar HTTP/1.1                   1               0
19178                                         http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=marielle&password=eNUmer24&nombre=Lahuen&apellidos=Carre+Mamani&email=vadim@drae2.ci&dni=83154874F&direccion=C/+Rio+Agreira+91+&ciudad=Ametlla+de+Mar,+L'&cp=46369&provincia=Badajoz&ntc=4626512497808574&B1=Registrar HTTP/1.1                   1               0
19238                       http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=dyment&password=MA724-3rA&nombre=Mirko&apellidos=Castells+Rel&email=daughtry@thecupidhouse.az&dni=07951538R&direccion=Calle+Tulipanes+151,+9?D&ciudad=Sant+Mart�+d'Albars&cp=03134&provincia=Palencia&ntc=8648898617825850&B1=Registrar HTTP/1.1                   1               0

In [91]:
print(
    df.groupby("classification")["encoded_sequence_count"].agg(
        ["mean", "median", "max"]
    )
)

                    mean  median  max
classification
0               0.265944     0.0   12
1               1.902573     0.0  114

In [92]:
print(
    df.loc[
        df["special_char_count"] > 0,
        [
            "url_decoded",
            "special_char_count",
            "classification"
        ]
    ].head(30).to_string()
)

                                                                                                                                                                                                                                                                                                                                        url_decoded  special_char_count  classification
350                                        http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=maurie&password=0StroP5je0&nombre=Vlentina&apellidos=Fisas&email=marlaud_losee5@redesmilitantes.tf&dni=54430634F&direccion=Viseu+81+8?C&ciudad=Corbera+d'Ebre&cp=48210&provincia=Murcia&ntc=4713791605534130&B1=Registrar HTTP/1.1                   1               0
530                         http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=threader&password=dESCOlocaDO&nombre=Mallki&apellidos=Moreno+Undurraga&email=stevenin@ceramicasmi�o.mn&dni=70153244R&direccion=C/+Vapor,+148,+2?A&ciudad=Espluga+Calba,+L'&cp=03153&provincia=Palencia&ntc=5838987688567542&B1=Registrar HTTP/1.1                   1               0
1850                        http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=jean-yve&password=reTEjAdOR&nombre=Cancia&apellidos=O'Kinghtons+Camarena&email=olrich-shapiro1@nuriamartin.aw&dni=97060354D&direccion=Senda+Buen+Paso+S/N,+&ciudad=Luesia&cp=22390&provincia=Asturias&ntc=8267431025409914&B1=Registrar HTTP/1.1                   1               0
2390                   http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=doan7&password=mil�sima&nombre=Yaideem&apellidos=Penido+Maym'o&email=olaughlin@pinkplanetplasencia.uy&dni=37662577P&direccion=Avenida+San+Francisco+Javier,+5,+&ciudad=D�lar&cp=24324&provincia=Valladolid&ntc=2781714156257998&B1=Registrar HTTP/1.1                   1               0
2618                                     http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=pomeroy5&password=C5fRA98&nombre=Bonifacio&apellidos=Iranzo&email=wyle@designworld.us&dni=88356550A&direccion=C/+Ca+N'alzina,+80,+6-B&ciudad=Requena+de+Campos&cp=45110&provincia=Granada&ntc=8995996565558024&B1=Registrar HTTP/1.1                   1               0
3326                               http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=boisvert&password=ma27ta&nombre=Paladio&apellidos=D'Amico+Urrea&email=mcnear.trotta@lettere.ve&dni=11295198J&direccion=Robert+Graves,+101+&ciudad=Casillas+de+Flores&cp=50300&provincia=Madrid&ntc=1889610781907232&B1=Registrar HTTP/1.1                   1               0
3590                                http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=bekki&password=retinte&nombre=Harry&apellidos=Capella+Gorr�n&email=gunner@piaceredelivery.kw&dni=78532141K&direccion=Isabel+La+Catolica,+34+&ciudad=Ribera+d'Ondara&cp=08250&provincia=Ourense&ntc=7930754215612383&B1=Registrar HTTP/1.1                   1               0
4010                                  http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=rec&password=CuITADa&nombre=Nahir&apellidos=Espineta+Astorquiza&email=pager@cocheacoche.ws&dni=85673796S&direccion=Calle+Francisco+De+Leiva,+131,+&ciudad=Aldea,+L'&cp=44143&provincia=Le�n&ntc=7590918469472640&B1=Registrar HTTP/1.1                   1               0
4022            http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=tyler&password=Sa?BalErO&nombre=Didier&apellidos=Medel+Pujolriu&email=scely_prono@tobarisch.de&dni=63375335P&direccion=C/+Leopoldo+Alas+"clarin"+4,+6?B&ciudad=Sant+Lloren�+de+la+Muga&cp=46712&provincia=Palencia&ntc=1693717556836495&B1=Registrar HTTP/1.1                   2               0
4154                     http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=gates&password=fol0aDo&nombre=Genciano&apellidos=Cedo+Rosa's&email=kepinska@manuelpaloma.asia&dni=42808198T&direccion=Plza.+Santa+Maria+96+8?F&ciudad=Santa+Mar�a+de+la+Vega&cp=11639&provincia=La+Rioja&ntc=9122440516217949&B1=Registrar HTTP/1.1                   1               0
4202                                      http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=zarrabia&password=apo9�0ICO&nombre=Orion&apellidos=Linares+Queralto&email=nanook@cup-id.lu&dni=03199923W&direccion=Ronda+O'donnell,+106,+12?E&ciudad=Oj�s&cp=34419&provincia=Ciudad+Real&ntc=7298091091245974&B1=Registrar HTTP/1.1                   1               0
7766                      http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=rollie&password=p21urit56&nombre=Calistrato&apellidos=Correa+Cachopo&email=charlots7@e-b-s.bm&dni=63482988K&direccion=Calle+De+Circulacio+De+L'+Oest,+7+&ciudad=Osornillo&cp=05192&provincia=Guadalajara&ntc=2910118261122194&B1=Registrar HTTP/1.1                   1               0
7874                                                    http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=gittins&password=36lis8r&nombre=Katia&apellidos=Luque&email=clay@parcalia.ml&dni=92152955M&direccion=Font+D'en+Canyelles+21,+1-B&ciudad=Montseny&cp=02215&provincia=Toledo&ntc=8096640532589515&B1=Registrar HTTP/1.1                   1               0
8198                http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=vyza&password=DiSIPAr&nombre=Argelio&apellidos=Palau+Ustrell&email=greenhalgh@cafedeteatro.np&dni=81180031J&direccion=Cayetano+Polo+"polito"+90+2?A&ciudad=Santa+Mar�a+de+las+Hoyas&cp=28609&provincia=Badajoz&ntc=6449111559125327&B1=Registrar HTTP/1.1                   2               0
8870                        http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=zimmerer&password=gre�a&nombre=Adriel&apellidos=Llena+Astall�&email=olesen@ballobar.com.mr&dni=08071780E&direccion=Etorbidea+Atarrabiako+126,+5D&ciudad=Castell�+d'Emp�ries&cp=34492&provincia=Toledo&ntc=9301738715220065&B1=Registrar HTTP/1.1                   1               0
9734                      http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=zarlenga&password=anabaptismo&nombre=Bertoldo&apellidos=Lapaza+O'Neil&email=poncin@todobetis.mil&dni=58193627Q&direccion=Pasadizo+Fernandez+92+3-C&ciudad=Churriana+de+la+Vega&cp=06656&provincia=C�diz&ntc=8336103681905855&B1=Registrar HTTP/1.1                   1               0
9854                            http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=eva&password=animador!a&nombre=Alonso&apellidos=Chanes+Galvan&email=congregation@saludyfitness.pm&dni=08109487D&direccion=C/+Era+Val+D'aran+S/N,+7?E&ciudad=Benabarre&cp=43440&provincia=Salamanca&ntc=3685717385941815&B1=Registrar HTTP/1.1                   1               0
9998                                              http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=offers&password=orGullEZA&nombre=Hoel&apellidos=Estic�+O'Neil&email=bashan@lettere.pr&dni=49339665L&direccion=Cami�o+Da+Mina,+175,+&ciudad=Oroz-Betelu&cp=38690&provincia=Madrid&ntc=7714584958323378&B1=Registrar HTTP/1.1                   1               0
11726                                                       http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=kaneko&password=18l4et2ro&nombre=Ayen&apellidos=Anglaril&email=spradlin@pcvirus.dz&dni=65456048A&direccion=De+L'+Aliga+3,+&ciudad=Almadrones&cp=47110&provincia=M�laga&ntc=5861000706039696&B1=Registrar HTTP/1.1                   1               0
13046                                 http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=andries&password=bezante&nombre=Nicasio&apellidos=Suau+Feixa&email=hardwick@corjet.gh&dni=97084633T&direccion=Partida+Lliriet+D'en+Mig,+135,+10?A&ciudad=Villena&cp=46269&provincia=Navarra&ntc=4641290123831700&B1=Registrar HTTP/1.1                   1               0
13694  http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=triantap&password=arpe*nde&nombre=Alor&apellidos=De+Lagarza+Delacerda&email=felber@hiperespa�a.ps&dni=87179467Z&direccion=Calle+Poligon+Industrial+"el+Segre",+118+&ciudad=Vilanova+de+Arousa&cp=31790&provincia=Salamanca&ntc=3548348718435303&B1=Registrar HTTP/1.1                   2               0
14246                                            http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=mathieso&password=pesantez&nombre=Trinidad&apellidos=Mc'Morral+Obrist&email=jolley@decoaching.na&dni=50535908D&direccion=Azorin+35+1B&ciudad=Padiernos&cp=25613&provincia=Sevilla&ntc=8120300504791286&B1=Registrar HTTP/1.1                   1               0
14270                                        http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=gdowik2&password=29?em2ti3a&nombre=Grecia&apellidos=Ar�n+Pola&email=fravel@filtraciondehumos.sz&dni=48171319G&direccion=El+Vito,+90+&ciudad=Ampolla,+L'&cp=50100&provincia=Castell�n&ntc=1798713909636768&B1=Registrar HTTP/1.1                   1               0
14282                            http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=silvia&password=chuchazo&nombre=Antoliano&apellidos=Benajas+Rodr�guez&email=pearcy@b-sign.mz&dni=10560589R&direccion=C/+De+La+Riera+D'horta+105,+5?H&ciudad=Duesaig�es&cp=46725&provincia=Navarra&ntc=2409731978356224&B1=Registrar HTTP/1.1                   1               0
14378                                   http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=mariabel&password=c2645ido&nombre=Zelma&apellidos=Dotor+Fornell&email=celik-regan@turinga.sb&dni=95113653M&direccion=Carrer+Jaume+D'artes+78,+&ciudad=Osornillo&cp=10411&provincia=Burgos&ntc=3090147546194865&B1=Registrar HTTP/1.1                   1               0
15866                                   http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=bolly&password=pintarrajar&nombre=Gontr�n&apellidos=Tanquia+Jepus&email=mccollon@irmedia.ca&dni=38507707A&direccion=C/+Costa+i+Llobera+83+&ciudad=Corbera+d'Ebre&cp=18339&provincia=Madrid&ntc=3820743619643877&B1=Registrar HTTP/1.1                   1               0
16466                      http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=addons&password=14ab214c6�n&nombre=Karla&apellidos=Jauregui+Cortines&email=quartet@cabare.com.cs&dni=86800649Y&direccion=Paratge+Lila+30,+10?C&ciudad=Espluga+de+Francol�,+L'&cp=06380&provincia=�vila&ntc=9091453994786923&B1=Registrar HTTP/1.1                   1               0
18626                                 http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=soules&password=acomplexionada&nombre=Rigby&apellidos=Pascuet+Landivar&email=moskuna@sitcpla.ye&dni=45053569L&direccion=Duende,+138,+&ciudad=Guingueta+d'�neu,+La&cp=40170&provincia=Huesca&ntc=0029687955884916&B1=Registrar HTTP/1.1                   1               0
19178                                         http://localhost:8080/tienda1/miembros/editar.jsp?modo=registro&login=marielle&password=eNUmer24&nombre=Lahuen&apellidos=Carre+Mamani&email=vadim@drae2.ci&dni=83154874F&direccion=C/+Rio+Agreira+91+&ciudad=Ametlla+de+Mar,+L'&cp=46369&provincia=Badajoz&ntc=4626512497808574&B1=Registrar HTTP/1.1                   1               0
19238                       http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=dyment&password=MA724-3rA&nombre=Mirko&apellidos=Castells+Rel&email=daughtry@thecupidhouse.az&dni=07951538R&direccion=Calle+Tulipanes+151,+9?D&ciudad=Sant+Mart�+d'Albars&cp=03134&provincia=Palencia&ntc=8648898617825850&B1=Registrar HTTP/1.1                   1               0

In [94]:
print(
    pd.crosstab(
        df["method"],
        df["classification"],
        normalize="columns"
    )*100
)

classification          0          1
method
GET             77.777778  60.195492
POST            22.222222  38.220626
PUT              0.000000   1.583882

In [97]:
print(df["user_agent"].value_counts().head(20))

user_agent
Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko)    61065
Name: count, dtype: int64

In [99]:
print(
    df.groupby("classification")["user_agent"]
      .nunique()
)

classification
0    1
1    1
Name: user_agent, dtype: int64

In [100]:
df["method_get"]=(
    df["method"].astype(str).str.upper()=="GET"
).astype(int)

df["method_post"]=(
    df["method"].astype(str).str.upper()=="POST"
).astype(int)

df["method_put"]=(
    df["method"].astype(str).str.upper()=="PUT"
).astype(int)

In [101]:
df["has_content"] = (
    df["content"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
).astype(int)

In [102]:
print(
    pd.crosstab(
        df["has_content"],
        df["classification"],
        normalize="columns"
    ) * 100
)

classification          0          1
has_content
0               77.777778  60.195492
1               22.222222  39.804508

In [104]:
df["content_length"] = (
    df["content"]
    .fillna("")
    .astype(str)
    .str.len()
)

print(
    df.groupby("classification")["content_length"].agg(
        ["mean", "median", "max"]
    )
)

                     mean  median  max
classification
0               20.347056     0.0  307
1               48.583004     0.0  836

In [105]:
print(
    df["user_agent"]
    .value_counts()
    .head(20)
)

user_agent
Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko)    61065
Name: count, dtype: int64

In [106]:
df["content_encoded_count"]=(
    df["content"]
    .fillna("")
    .astype(str)
    .apply(
        lambda x: len(re.findall(r"%[0-9A-Fa-f]{2}", x))
    )
)

In [107]:
print(
    df.groupby("classification")["content_encoded_count"].agg(
        ["mean", "median", "max"]
    )
)

                    mean  median  max
classification
0               0.265944     0.0   12
1               1.923599     0.0  114

In [108]:
content_special_chars = """'"><;%"""

df["content_special_char_count"] = (
    df["content"]
    .fillna("")
    .astype(str)
    .apply(
        lambda x: sum(
            char in content_special_chars
            for char in x
        )
    )
)

In [109]:
print(
    df.groupby("classification")["content_special_char_count"].agg(
        ["mean", "median", "max"]
    )
)

                    mean  median  max
classification
0               0.265944     0.0   12
1               1.923599     0.0  114

In [110]:
print(
    df.groupby("classification")["user_agent"].nunique()
)

classification
0    1
1    1
Name: user_agent, dtype: int64

In [111]:
print(
    df["user_agent"]
    .value_counts()
    .head(20)
)

user_agent
Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.8 (like Gecko)    61065
Name: count, dtype: int64

In [113]:
print(
    df["user_agent"].isna().sum()
)

0

In [114]:
print(
    df[
        [
            "url_raw",
            "content",
            "encoded_sequence_count",
            "content_encoded_count",
            "classification"
        ]
    ].head(20).to_string()
)

                                                                                                                                                                                                                                                                                                 url_raw                                                                                                                                                                                                                                   content  encoded_sequence_count  content_encoded_count  classification
0                                                                                                                                                                                                                                                       http://localhost:8080/tienda1/index.jsp HTTP/1.1                                                                                                                                                                                                                                       NaN                       0                      0               0
1                                                                                                                                                                         http://localhost:8080/tienda1/publico/anadir.jsp?id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A%F1adir+al+carrito HTTP/1.1                                                                                                                                                                                                                                       NaN                       1                      0               0
2                                                                                                                                                                                                                                              http://localhost:8080/tienda1/publico/anadir.jsp HTTP/1.1                                                                                                                                                                      id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A%F1adir+al+carrito                       0                      1               0
3                                                                                                                                                                          http://localhost:8080/tienda1/publico/autenticar.jsp?modo=entrar&login=choong&pwd=d1se3ci%F3n&remember=off&B1=Entrar HTTP/1.1                                                                                                                                                                                                                                       NaN                       1                      0               0
4                                                                                                                                                                                                                                          http://localhost:8080/tienda1/publico/autenticar.jsp HTTP/1.1                                                                                                                                                                           modo=entrar&login=choong&pwd=d1se3ci%F3n&remember=off&B1=Entrar                       0                      1               0
5                                                                                                                                                                                                                                http://localhost:8080/tienda1/publico/caracteristicas.jsp?id=2 HTTP/1.1                                                                                                                                                                                                                                       NaN                       0                      0               0
6                                                                                                                                                                                                                                     http://localhost:8080/tienda1/publico/caracteristicas.jsp HTTP/1.1                                                                                                                                                                                                                                      id=2                       0                      0               0
7                                                                                                                                                                                                                                             http://localhost:8080/tienda1/publico/carrito.jsp HTTP/1.1                                                                                                                                                                                                                                       NaN                       0                      0               0
8                                                                                                                                                                                                            http://localhost:8080/tienda1/publico/entrar.jsp?errorMsg=Credenciales+incorrectas HTTP/1.1                                                                                                                                                                                                                                       NaN                       0                      0               0
9                                                                                                                                                                                                                                              http://localhost:8080/tienda1/publico/entrar.jsp HTTP/1.1                                                                                                                                                                                                         errorMsg=Credenciales+incorrectas                       0                      0               0
10                                                                                                                                                                                                                                           http://localhost:8080/tienda1/publico/miembros.jsp HTTP/1.1                                                                                                                                                                                                                                       NaN                       0                      0               0
11                                                                                                                                                                                                  http://localhost:8080/tienda1/publico/pagar.jsp?modo=insertar&precio=2672&B1=Pasar+por+caja HTTP/1.1                                                                                                                                                                                                                                       NaN                       0                      0               0
12                                                                                                                                                                                                                                              http://localhost:8080/tienda1/publico/pagar.jsp HTTP/1.1                                                                                                                                                                                               modo=insertar&precio=2672&B1=Pasar+por+caja                       0                      0               0
13                                                                                                                                                                                                                                          http://localhost:8080/tienda1/publico/productos.jsp HTTP/1.1                                                                                                                                                                                                                                       NaN                       0                      0               0
14  http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=cen&password=40a5E&nombre=Nurit&apellidos=Ferrandez+Caba%F1as&email=tarpey%40bwds.ne&dni=17621392B&direccion=Calle+Clavel+30+11%3FB&ciudad=Tronch%F3n&cp=17463&provincia=C%E1ceres&ntc=1527409541807001&B1=Registrar HTTP/1.1                                                                                                                                                                                                                                       NaN                       5                      0               0
15                                                                                                                                                                                                                                           http://localhost:8080/tienda1/publico/registro.jsp HTTP/1.1  modo=registro&login=cen&password=40a5E&nombre=Nurit&apellidos=Ferrandez+Caba%F1as&email=tarpey%40bwds.ne&dni=17621392B&direccion=Calle+Clavel+30+11%3FB&ciudad=Tronch%F3n&cp=17463&provincia=C%E1ceres&ntc=1527409541807001&B1=Registrar                       0                      5               0
16                                                                                                                                                                                                                           http://localhost:8080/tienda1/publico/vaciar.jsp?B2=Vaciar+carrito HTTP/1.1                                                                                                                                                                                                                                       NaN                       0                      0               0
17                                                                                                                                                                                                                                             http://localhost:8080/tienda1/publico/vaciar.jsp HTTP/1.1                                                                                                                                                                                                                         B2=Vaciar+carrito                       0                      0               0
18                                                                                                                                                                                                                                            http://localhost:8080/tienda1/global/creditos.jsp HTTP/1.1                                                                                                                                                                                                                                       NaN                       0                      0               0
19                                                                                                                                                                                                                                               http://localhost:8080/tienda1/global/menum.jsp HTTP/1.1                                                                                                                                                                                                                                       NaN                       0                      0               0

In [115]:
print(
    (df["encoded_sequence_count"] == df["content_encoded_count"]).mean()
)

0.649635634160321

In [117]:
print(
    df[
        [
            "url",
            "content",
            "encoded_sequence_count",
            "content_encoded_count",
            "classification"
        ]
    ].head(20).to_string()
)

print(
    "Same values percentage:",
    (
        df["encoded_sequence_count"]
        == df["content_encoded_count"]
    ).mean()
)

                                                                                                                                                                                                                                                                                            url                                                                                                                                                                                                                                   content  encoded_sequence_count  content_encoded_count  classification
0                                                                                                                                                                                                                                                       http://localhost:8080/tienda1/index.jsp                                                                                                                                                                                                                                       NaN                       0                      0               0
1                                                                                                                                                                         http://localhost:8080/tienda1/publico/anadir.jsp?id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A%F1adir+al+carrito                                                                                                                                                                                                                                       NaN                       1                      0               0
2                                                                                                                                                                                                                                              http://localhost:8080/tienda1/publico/anadir.jsp                                                                                                                                                                      id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A%F1adir+al+carrito                       0                      1               0
3                                                                                                                                                                          http://localhost:8080/tienda1/publico/autenticar.jsp?modo=entrar&login=choong&pwd=d1se3ci%F3n&remember=off&B1=Entrar                                                                                                                                                                                                                                       NaN                       1                      0               0
4                                                                                                                                                                                                                                          http://localhost:8080/tienda1/publico/autenticar.jsp                                                                                                                                                                           modo=entrar&login=choong&pwd=d1se3ci%F3n&remember=off&B1=Entrar                       0                      1               0
5                                                                                                                                                                                                                                http://localhost:8080/tienda1/publico/caracteristicas.jsp?id=2                                                                                                                                                                                                                                       NaN                       0                      0               0
6                                                                                                                                                                                                                                     http://localhost:8080/tienda1/publico/caracteristicas.jsp                                                                                                                                                                                                                                      id=2                       0                      0               0
7                                                                                                                                                                                                                                             http://localhost:8080/tienda1/publico/carrito.jsp                                                                                                                                                                                                                                       NaN                       0                      0               0
8                                                                                                                                                                                                            http://localhost:8080/tienda1/publico/entrar.jsp?errorMsg=Credenciales+incorrectas                                                                                                                                                                                                                                       NaN                       0                      0               0
9                                                                                                                                                                                                                                              http://localhost:8080/tienda1/publico/entrar.jsp                                                                                                                                                                                                         errorMsg=Credenciales+incorrectas                       0                      0               0
10                                                                                                                                                                                                                                           http://localhost:8080/tienda1/publico/miembros.jsp                                                                                                                                                                                                                                       NaN                       0                      0               0
11                                                                                                                                                                                                  http://localhost:8080/tienda1/publico/pagar.jsp?modo=insertar&precio=2672&B1=Pasar+por+caja                                                                                                                                                                                                                                       NaN                       0                      0               0
12                                                                                                                                                                                                                                              http://localhost:8080/tienda1/publico/pagar.jsp                                                                                                                                                                                               modo=insertar&precio=2672&B1=Pasar+por+caja                       0                      0               0
13                                                                                                                                                                                                                                          http://localhost:8080/tienda1/publico/productos.jsp                                                                                                                                                                                                                                       NaN                       0                      0               0
14  http://localhost:8080/tienda1/publico/registro.jsp?modo=registro&login=cen&password=40a5E&nombre=Nurit&apellidos=Ferrandez+Caba%F1as&email=tarpey%40bwds.ne&dni=17621392B&direccion=Calle+Clavel+30+11%3FB&ciudad=Tronch%F3n&cp=17463&provincia=C%E1ceres&ntc=1527409541807001&B1=Registrar                                                                                                                                                                                                                                       NaN                       5                      0               0
15                                                                                                                                                                                                                                           http://localhost:8080/tienda1/publico/registro.jsp  modo=registro&login=cen&password=40a5E&nombre=Nurit&apellidos=Ferrandez+Caba%F1as&email=tarpey%40bwds.ne&dni=17621392B&direccion=Calle+Clavel+30+11%3FB&ciudad=Tronch%F3n&cp=17463&provincia=C%E1ceres&ntc=1527409541807001&B1=Registrar                       0                      5               0
16                                                                                                                                                                                                                           http://localhost:8080/tienda1/publico/vaciar.jsp?B2=Vaciar+carrito                                                                                                                                                                                                                                       NaN                       0                      0               0
17                                                                                                                                                                                                                                             http://localhost:8080/tienda1/publico/vaciar.jsp                                                                                                                                                                                                                         B2=Vaciar+carrito                       0                      0               0
18                                                                                                                                                                                                                                            http://localhost:8080/tienda1/global/creditos.jsp                                                                                                                                                                                                                                       NaN                       0                      0               0
19                                                                                                                                                                                                                                               http://localhost:8080/tienda1/global/menum.jsp                                                                                                                                                                                                                                       NaN                       0                      0               0
Same values percentage: 0.649635634160321

In [118]:
df["cookie_length"]=(
    df["cookie"]
    .fillna("")
    .astype(str)
    .str.len()
)

print(
    df.groupby("classification")["cookie_length"].agg(
        ["mean", "median", "max"]
    )
)

                mean  median  max
classification
0               43.0    43.0   43
1               43.0    43.0   43

In [119]:
print(
    df.groupby("classification")["cookie"].nunique()
)

classification
0    36000
1    25065
Name: cookie, dtype: int64

In [121]:
print(
    df["content_type"]
    .fillna("Missing")
    .value_counts()
)

content_type
Missing                              43088
application/x-www-form-urlencoded    17977
Name: count, dtype: int64

In [122]:
print(
    pd.crosstab(
        df["content_type"].fillna("Missing"),
        df["classification"],
        normalize="columns"
    ) * 100
)

classification                             0          1
content_type
Missing                            77.777778  60.195492
application/x-www-form-urlencoded  22.222222  39.804508

In [123]:
df["has_cookie"] = (
    df["cookie"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
).astype(int)

In [124]:
print(
    pd.crosstab(
        df["has_cookie"],
        df["classification"],
        normalize="columns"
    ) * 100
)

classification      0      1
has_cookie
1               100.0  100.0

In [125]:
print(
    df.groupby("classification")["cookie_length"].agg(
        ["mean", "median", "max"]
    )
)

                mean  median  max
classification
0               43.0    43.0   43
1               43.0    43.0   43

In [126]:
df["cookie_parameter_count"] = (
    df["cookie"]
    .fillna("")
    .astype(str)
    .apply(
        lambda x: 0 if not x.strip()
        else len([p for p in x.split(";") if p.strip()])
    )
)

print(
    df.groupby("classification")["cookie_parameter_count"].agg(
        ["mean", "median", "max"]
    )
)

                mean  median  max
classification
0                1.0     1.0    1
1                1.0     1.0    1

In [128]:
df["is_form_urlencoded"] = (
    df["content_type"]
    .fillna("")
    .astype(str)
    .str.lower()
    .eq("application/x-www-form-urlencoded")
).astype(int)

In [129]:
print(
    pd.crosstab(
        df["is_form_urlencoded"],
        df["classification"],
        normalize="columns"
    ) * 100
)

classification              0          1
is_form_urlencoded
0                   77.777778  60.195492
1                   22.222222  39.804508

In [130]:
print(
    pd.crosstab(
        df["is_form_urlencoded"],
        df["classification"]
    )
)

classification          0      1
is_form_urlencoded
0                   28000  15088
1                    8000   9977

In [131]:
df.drop(columns=["has_cookie"], inplace=True)

In [132]:
df.drop(columns=["cookie_length"], inplace=True)

In [133]:
df.drop(columns=["cookie_parameter_count"], inplace=True)

In [134]:
df["security_text"]=(
    df["url"].fillna("").astype(str)
    +" "
    +df["content"].fillna("").astype(str)
)

In [135]:
sql_keywords = [
    "select",
    "union",
    "insert",
    "update",
    "delete",
    "drop",
    "alter",
    "create",
    "from",
    "where",
    "having",
    "order by",
    "group by"
]

In [136]:
import re

def count_sql_keywords(text):
    text = str(text).lower()
    return sum(
        len(re.findall(r"\b" + re.escape(word) + r"\b", text))
        for word in sql_keywords
    )

df["sql_keyword_count"] = (
    df["security_text"]
    .apply(count_sql_keywords)
)

In [137]:
sql_comment_pattern = r"--|/\*|\*/|#"

df["sql_comment_count"] = (
    df["security_text"]
    .str.count(sql_comment_pattern)
)

In [138]:
df["single_quote_count"] = (
    df["security_text"].str.count("'")
)

df["double_quote_count"] = (
    df["security_text"].str.count('"')
)

In [139]:
sql_logic_pattern = r"\b(and|or)\b"

df["sql_logic_count"] = (
    df["security_text"]
    .str.lower()
    .str.count(sql_logic_pattern)
)

In [140]:
sqli_features = [
    "sql_keyword_count",
    "sql_comment_count",
    "single_quote_count",
    "double_quote_count",
    "sql_logic_count"
]

print(
    df.groupby("classification")[sqli_features].agg(
        ["mean", "median", "max"]
    )
)

               sql_keyword_count            sql_comment_count             \
                            mean median max              mean median max
classification
0                       0.000111    0.0   1          0.000000    0.0   0
1                       0.044883    0.0   4          0.101815    0.0   2

               single_quote_count            double_quote_count             \
                             mean median max               mean median max
classification
0                             0.0    0.0   0                0.0    0.0   0
1                             0.0    0.0   0                0.0    0.0   0

               sql_logic_count
                          mean median max
classification
0                     0.000278    0.0   1
1                     0.017235    0.0   1

In [141]:
df.drop(
    columns=["single_quote_count", "double_quote_count"],
    inplace=True
)

In [142]:
df["security_text"]

0                 http://localhost:8080/tienda1/index.jsp
1        http://localhost:8080/tienda1/publico/anadir.j...
2        http://localhost:8080/tienda1/publico/anadir.j...
3        http://localhost:8080/tienda1/publico/autentic...
4        http://localhost:8080/tienda1/publico/autentic...
                               ...
61060    http://localhost:8080/tienda1/miembros/editar....
61061    http://localhost:8080/tienda1/miembros/editar....
61062    http://localhost:8080/tienda1/miembros/editar....
61063       http://localhost:8080/tienda1/imagenes/3.gif/
61064    http://localhost:8080/tienda1/imagenes/nuestra...
Name: security_text, Length: 61065, dtype: object

In [144]:
xss_tag_pattern=r"<\s*(script|iframe|img|svg|object|embed|html|body|)\b"

df["xss_tag_count"]=(
    df["security_text"]
    .str.lower()
    .str.count(xss_tag_pattern)
)

In [151]:
df["script_keyboard_count"]=(
    df["security_text"]
    .str.lower()
    .str.count(r"\bscript\b")
)

In [146]:
df["javascript_keyword_count"] = (
    df["security_text"]
    .str.lower()
    .str.count(r"javascript\s*:")
)

In [147]:
event_handler_pattern=(
    r"\bon(click|error|load|mouseover|focus|submit|change)\s*="
)

df["event_handler_count"]=(
    df["security_text"]
    .str.lower()
    .str.count(event_handler_pattern)
)

In [152]:
xss_features = [
    "xss_tag_count",
    "script_keyword_count",
    "javascript_keyword_count",
    "event_handler_count"
]

print("Available columns:")
print(df.columns.tolist())

print("\nMissing XSS columns:")
print([col for col in xss_features if col not in df.columns])

Available columns:
['unnamed:_0', 'method', 'user_agent', 'pragma', 'cache_control', 'accept', 'accept_encoding', 'accept_charset', 'language', 'host', 'cookie', 'content_type', 'connection', 'lenght', 'content', 'classification', 'url', 'url_raw', 'scheme', 'url_host', 'port', 'path', 'query', 'parameter_count', 'url_length', 'path_length', 'query_length', 'url_decoded', 'query_decoded', 'special_char_count', 'encoding_count', 'path_depth', 'encoded_sequence_count', 'slash_count', 'dot_count', 'question_mark_count', 'ampersand_count', 'sql_keyword_count', 'sql_special_count', 'sql_comment_count', 'sql_logic_count', 'has_sql_keyword', 'has_sql_comment', 'sql_operator_count', 'has_encoding', 'query_sql_keyword_count', 'method_get', 'method_post', 'method_put', 'has_content', 'content_length', 'content_encoded_count', 'content_special_char_count', 'is_form_urlencoded', 'security_text', 'xss_tag_count', 'script_keyboard_count', 'javascript_keyword_count', 'event_handler_count']

Missing XSS columns:
['script_keyword_count']

In [149]:
df.head(4)

,unnamed:_0,method,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,host,...,has_content,content_length,content_encoded_count,content_special_char_count,is_form_urlencoded,security_text,xss_tag_count,script_keyboard_count,javascript_keyword_count,event_handler_count
0,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,...,0,0,0,0,0,http://localhost:8080/tienda1/index.jsp,0,0,0,0
1,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,...,0,0,0,0,0,http://localhost:8080/tienda1/publico/anadir.j...,0,0,0,0
2,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,...,1,68,1,1,1,http://localhost:8080/tienda1/publico/anadir.j...,0,0,0,0
3,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,...,0,0,0,0,0,http://localhost:8080/tienda1/publico/autentic...,0,0,0,0

In [153]:
df.rename(
    columns={
        "script_keyboard_count": "script_keyword_count"
    },
    inplace=True
)

In [154]:
print("script_keyword_count" in df.columns)

True

In [155]:
xss_features = [
    "xss_tag_count",
    "script_keyword_count",
    "javascript_keyword_count",
    "event_handler_count"
]

print(
    df.groupby("classification")[xss_features].agg(
        ["mean", "median", "max"]
    )
)

               xss_tag_count            script_keyword_count             \
                        mean median max                 mean median max
classification
0                        0.0    0.0   0                  0.0    0.0   0
1                        0.0    0.0   0                  0.0    0.0   0

               javascript_keyword_count            event_handler_count         \
                                   mean median max                mean median
classification
0                                   0.0    0.0   0                 0.0    0.0
1                                   0.0    0.0   0                 0.0    0.0


               max
classification
0                0
1                0