In [2]:
import pandas as pd
import numpy as np
import re
import html

from urllib.parse import unquote, urlparse

In [3]:
df=pd.read_csv('csic_database.csv')

In [5]:
df.head(5)

,Unnamed: 0,Method,User-Agent,Pragma,Cache-Control,Accept,Accept-encoding,Accept-charset,language,host,cookie,content-type,connection,lenght,content,classification,URL
0,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...

In [7]:
df.describe()

       classification
count    61065.000000
mean         0.410464
std          0.491922
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          1.000000

In [8]:
print(df.shape)

(61065, 17)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61065 entries, 0 to 61064
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       61065 non-null  object
 1   Method           61065 non-null  object
 2   User-Agent       61065 non-null  object
 3   Pragma           61065 non-null  object
 4   Cache-Control    61065 non-null  object
 5   Accept           60668 non-null  object
 6   Accept-encoding  61065 non-null  object
 7   Accept-charset   61065 non-null  object
 8   language         61065 non-null  object
 9   host             61065 non-null  object
 10  cookie           61065 non-null  object
 11  content-type     17977 non-null  object
 12  connection       61065 non-null  object
 13  lenght           17977 non-null  object
 14  content          17977 non-null  object
 15  classification   61065 non-null  int64
 16  URL              61065 non-null  object
dtypes: int64(1), object(16)
memory usage: 7.9+ MB

In [11]:
print(df.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['Unnamed: 0', 'Method', 'User-Agent', 'Pragma', 'Cache-Control',
       'Accept', 'Accept-encoding', 'Accept-charset', 'language', 'host',
       'cookie', 'content-type', 'connection', 'lenght', 'content',
       'classification', 'URL'],
      dtype='object')>

In [13]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

In [14]:
df.head()

,unnamed:_0,method,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,host,cookie,content_type,connection,lenght,content,classification,url
0,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...

In [15]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [17]:
print(df.columns.tolist())

['unnamed:_0', 'method', 'user_agent', 'pragma', 'cache_control', 'accept', 'accept_encoding', 'accept_charset', 'language', 'host', 'cookie', 'content_type', 'connection', 'lenght', 'content', 'classification', 'url']

In [18]:
if "Unnamed: 0" in df.columns:
    print(df["Unnamed: 0"].head(10))
    print(df["Unnamed: 0"].tail(10))
else:
    print("'Unnamed: 0' column does not exist")

'Unnamed: 0' column does not exist

In [20]:
print("Columns in df:")
print(df.columns.tolist())

print("\nShape:")
print(df.shape)

print("\nFirst 5 rows:")
display(df.head())

Columns in df:
['unnamed:_0', 'method', 'user_agent', 'pragma', 'cache_control', 'accept', 'accept_encoding', 'accept_charset', 'language', 'host', 'cookie', 'content_type', 'connection', 'lenght', 'content', 'classification', 'url']

Shape:
(61065, 17)

First 5 rows:

,unnamed:_0,method,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,host,cookie,content_type,connection,lenght,content,classification,url
0,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...

In [21]:
df.columns = df.columns.astype(str).str.strip()

print(df.columns.tolist())

['unnamed:_0', 'method', 'user_agent', 'pragma', 'cache_control', 'accept', 'accept_encoding', 'accept_charset', 'language', 'host', 'cookie', 'content_type', 'connection', 'lenght', 'content', 'classification', 'url']

In [22]:
if "Method" in df.columns:
    print(df["Method"].value_counts(dropna=False))
else:
    print("Method column NOT FOUND")

Method column NOT FOUND

In [23]:
method_col = [col for col in df.columns 
              if str(col).strip().lower() == "method"]

print(method_col)

['method']

In [24]:
print(df[method_col[0]].value_counts(dropna=False))

method
GET     43088
POST    17580
PUT       397
Name: count, dtype: int64

In [25]:
print(df["classification"].value_counts())

classification
0    36000
1    25065
Name: count, dtype: int64

In [26]:
print(
    df["classification"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

classification
0    58.95
1    41.05
Name: proportion, dtype: float64

In [ ]:
# 0 or 1 ko compare karne ke liye classification column ka use karenge. 0 ka matlab hai normal traffic aur 1 ka matlab hai attack traffic.
print("Available columns:")
print(df.columns.tolist())

print("\nCLASSIFICATION 0:")
display(
    df[df["classification"] == 0].head(10)
)

print("\nCLASSIFICATION 1:")
display(
    df[df["classification"] == 1].head(10)
)

Available columns:
['unnamed:_0', 'method', 'user_agent', 'pragma', 'cache_control', 'accept', 'accept_encoding', 'accept_charset', 'language', 'host', 'cookie', 'content_type', 'connection', 'lenght', 'content', 'classification', 'url']

CLASSIFICATION 0:

,unnamed:_0,method,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,host,cookie,content_type,connection,lenght,content,classification,url
0,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...
5,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=5254A7A7C7F0E74D699E6A9C9487795A,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/caracter...
6,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=417DBC69B2F909CCD574CFC69F56779F,application/x-www-form-urlencoded,Connection: close,Content-Length: 4,id=2,0,http://localhost:8080/tienda1/publico/caracter...
7,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=42B53DB3F82E67BBB24E57E9CDC8E008,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/carrito....
8,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=A651CE9798E1B71FCA9D9B2159432A22,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/entrar.j...
9,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=EE6A06EE8174FC2B05432AA5A0FCE998,application/x-www-form-urlencoded,Connection: close,Content-Length: 33,errorMsg=Credenciales+incorrectas,0,http://localhost:8080/tienda1/publico/entrar.j...

CLASSIFICATION 1:

,unnamed:_0,method,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,host,cookie,content_type,connection,lenght,content,classification,url
36000,Anomalous,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=B92A8B48B9008CD29F622A994E0F650D,NaN,close,NaN,NaN,1,http://localhost:8080/tienda1/publico/anadir.j...
36001,Anomalous,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=AE29AEEBDE479D5E1A18B4108C8E3CE0,application/x-www-form-urlencoded,Connection: close,Content-Length: 146,id=2&nombre=Jam%F3n+Ib%E9rico&precio=85&cantid...,1,http://localhost:8080/tienda1/publico/anadir.j...
36002,Anomalous,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=F563B5262843F12ECAE41815ABDEEA54,NaN,close,NaN,NaN,1,http://localhost:8080/tienda1/publico/anadir.j...
36003,Anomalous,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=3B654D6DF7F1466EE80D7F756B00E5D1,application/x-www-form-urlencoded,Connection: close,Content-Length: 77,id=2%2F&nombre=Jam%F3n+Ib%E9rico&precio=85&can...,1,http://localhost:8080/tienda1/publico/anadir.j...
36004,Anomalous,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=51A7470173188BBB993947F2283059E4,NaN,close,NaN,NaN,1,http://localhost:8080/asf-logo-wide.gif~ HTTP/1.1
36005,Anomalous,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=AC0EEEDD09663CB36C67DD1B787B0CF5,NaN,close,NaN,NaN,1,http://localhost:8080/tienda1/publico/autentic...
36006,Anomalous,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=D6037A58019A61C4E5745B952029D61F,application/x-www-form-urlencoded,Connection: close,Content-Length: 118,modo=entrar&login=bob%40%3CSCRipt%3Ealert%28Pa...,1,http://localhost:8080/tienda1/publico/autentic...
36007,Anomalous,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=0FCF23BE3D0EB007F5289208CE069EAA,NaN,close,NaN,NaN,1,http://localhost:8080/tienda1/publico/autentic...
36008,Anomalous,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8AF6B635AEBCD053B136669662597271,application/x-www-form-urlencoded,Connection: close,Content-Length: 69,modo=entrar&login=grimshaw&pwd=G%2F%2FlAc%2CIA...,1,http://localhost:8080/tienda1/publico/autentic...
36009,Anomalous,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=09BF818C8B6E9EFE9DF5F28745D5948B,NaN,close,NaN,NaN,1,http://localhost:8080/tienda1/publico/autentic...

In [32]:
df.head(5)

,unnamed:_0,method,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,host,cookie,content_type,connection,lenght,content,classification,url
0,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...

In [33]:
print("Total URLs:", df["url"].shape[0])
print("Unique URLs:", df["url"].nunique())

Total URLs: 61065
Unique URLs: 13498

In [35]:
print(df["url"].head(20).to_string(index=False))

  http://localhost:8080/tienda1/index.jsp HTTP/1.1
http://localhost:8080/tienda1/publico/anadir.js...
http://localhost:8080/tienda1/publico/anadir.js...
http://localhost:8080/tienda1/publico/autentica...
http://localhost:8080/tienda1/publico/autentica...
http://localhost:8080/tienda1/publico/caracteri...
http://localhost:8080/tienda1/publico/caracteri...
http://localhost:8080/tienda1/publico/carrito.j...
http://localhost:8080/tienda1/publico/entrar.js...
http://localhost:8080/tienda1/publico/entrar.js...
http://localhost:8080/tienda1/publico/miembros....
http://localhost:8080/tienda1/publico/pagar.jsp...
http://localhost:8080/tienda1/publico/pagar.jsp...
http://localhost:8080/tienda1/publico/productos...
http://localhost:8080/tienda1/publico/registro....
http://localhost:8080/tienda1/publico/registro....
http://localhost:8080/tienda1/publico/vaciar.js...
http://localhost:8080/tienda1/publico/vaciar.js...
http://localhost:8080/tienda1/global/creditos.j...
http://localhost:8080/tienda1/global/menum.jsp ...

In [40]:

# 1. Preserve original URL
df["url_raw"] = df["url"].copy()

# 2. Separate URL and HTTP version
def split_url_http(value):
    value = str(value).strip()

    match = re.match(
        r"^(.*?)(?:\s+)(HTTP/\d(?:\.\d)?)$",
        value
    )

    if match:
        return pd.Series({
            "url": match.group(1),
            "http_version": match.group(2)
        })

    return pd.Series({
        "url": value,
        "http_version": None
    })

df[["url", "http_version"]] = (
    df["url_raw"].apply(split_url_http)
)

# 3. Inspect
display(
    df[
        ["url_raw", "url", "http_version"]
    ].head(20)
)

# 4. Check HTTP versions
print("\nHTTP Version Distribution:")
print(df["http_version"].value_counts(dropna=False))

,url_raw,url,http_version
0,http://localhost:8080/tienda1/index.jsp,http://localhost:8080/tienda1/index.jsp,None
1,http://localhost:8080/tienda1/publico/anadir.j...,http://localhost:8080/tienda1/publico/anadir.j...,None
2,http://localhost:8080/tienda1/publico/anadir.jsp,http://localhost:8080/tienda1/publico/anadir.jsp,None
3,http://localhost:8080/tienda1/publico/autentic...,http://localhost:8080/tienda1/publico/autentic...,None
4,http://localhost:8080/tienda1/publico/autentic...,http://localhost:8080/tienda1/publico/autentic...,None
5,http://localhost:8080/tienda1/publico/caracter...,http://localhost:8080/tienda1/publico/caracter...,None
6,http://localhost:8080/tienda1/publico/caracter...,http://localhost:8080/tienda1/publico/caracter...,None
7,http://localhost:8080/tienda1/publico/carrito.jsp,http://localhost:8080/tienda1/publico/carrito.jsp,None
8,http://localhost:8080/tienda1/publico/entrar.j...,http://localhost:8080/tienda1/publico/entrar.j...,None
9,http://localhost:8080/tienda1/publico/entrar.jsp,http://localhost:8080/tienda1/publico/entrar.jsp,None
10,http://localhost:8080/tienda1/publico/miembros...,http://localhost:8080/tienda1/publico/miembros...,None
11,http://localhost:8080/tienda1/publico/pagar.js...,http://localhost:8080/tienda1/publico/pagar.js...,None
12,http://localhost:8080/tienda1/publico/pagar.jsp,http://localhost:8080/tienda1/publico/pagar.jsp,None
13,http://localhost:8080/tienda1/publico/producto...,http://localhost:8080/tienda1/publico/producto...,None
14,http://localhost:8080/tienda1/publico/registro...,http://localhost:8080/tienda1/publico/registro...,None
15,http://localhost:8080/tienda1/publico/registro...,http://localhost:8080/tienda1/publico/registro...,None
16,http://localhost:8080/tienda1/publico/vaciar.j...,http://localhost:8080/tienda1/publico/vaciar.j...,None
17,http://localhost:8080/tienda1/publico/vaciar.jsp,http://localhost:8080/tienda1/publico/vaciar.jsp,None
18,http://localhost:8080/tienda1/global/creditos.jsp,http://localhost:8080/tienda1/global/creditos.jsp,None
19,http://localhost:8080/tienda1/global/menum.jsp,http://localhost:8080/tienda1/global/menum.jsp,None

HTTP Version Distribution:
http_version
None    61065
Name: count, dtype: int64

In [42]:
for i in range(10):
    print(repr(df["url"].iloc[i]))

'http://localhost:8080/tienda1/index.jsp'
'http://localhost:8080/tienda1/publico/anadir.jsp?id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A%F1adir+al+carrito'
'http://localhost:8080/tienda1/publico/anadir.jsp'
'http://localhost:8080/tienda1/publico/autenticar.jsp?modo=entrar&login=choong&pwd=d1se3ci%F3n&remember=off&B1=Entrar'
'http://localhost:8080/tienda1/publico/autenticar.jsp'
'http://localhost:8080/tienda1/publico/caracteristicas.jsp?id=2'
'http://localhost:8080/tienda1/publico/caracteristicas.jsp'
'http://localhost:8080/tienda1/publico/carrito.jsp'
'http://localhost:8080/tienda1/publico/entrar.jsp?errorMsg=Credenciales+incorrectas'
'http://localhost:8080/tienda1/publico/entrar.jsp'

In [44]:
print(
    df["url"]
    .astype(str)
    .str.contains("HTTP/1.1", regex=False)
    .sum()
)

0

In [45]:
print(
    df["url"]
    .astype(str)
    .str.contains("HTTP/", regex=False)
    .sum()
)

0

In [46]:
df["http_version"]

0        None
1        None
2        None
3        None
4        None
         ...
61060    None
61061    None
61062    None
61063    None
61064    None
Name: http_version, Length: 61065, dtype: object

In [47]:
df.drop(columns=["http_version"], inplace=True)

In [49]:
print(repr(df["url"].iloc[1]))

'http://localhost:8080/tienda1/publico/anadir.jsp?id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A%F1adir+al+carrito'

In [52]:
#url parsing kar raha hu iss step
from urllib.parse import urlparse
import pandas as pd

def parse_url(url):
    try:
        parsed = urlparse(str(url).strip())

        # Safely extract port
        try:
            port = parsed.port
        except ValueError:
            port = None

        return pd.Series({
            "scheme": parsed.scheme,
            "url_host": parsed.hostname,
            "port": port,
            "path": parsed.path,
            "query": parsed.query
        })

    except Exception:
        return pd.Series({
            "scheme": None,
            "url_host": None,
            "port": None,
            "path": None,
            "query": None
        })


df[["scheme", "url_host", "port", "path", "query"]] = (
    df["url"].apply(parse_url)
)

In [54]:
display(
    df[
        ["url", "scheme", "url_host", "port", "path", "query"]
    ].head(10)
)

,url,scheme,url_host,port,path,query
0,http://localhost:8080/tienda1/index.jsp,http,localhost,8080.0,/tienda1/index.jsp,
1,http://localhost:8080/tienda1/publico/anadir.j...,http,localhost,8080.0,/tienda1/publico/anadir.jsp,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...
2,http://localhost:8080/tienda1/publico/anadir.jsp,http,localhost,8080.0,/tienda1/publico/anadir.jsp,
3,http://localhost:8080/tienda1/publico/autentic...,http,localhost,8080.0,/tienda1/publico/autenticar.jsp,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...
4,http://localhost:8080/tienda1/publico/autentic...,http,localhost,8080.0,/tienda1/publico/autenticar.jsp,
5,http://localhost:8080/tienda1/publico/caracter...,http,localhost,8080.0,/tienda1/publico/caracteristicas.jsp,id=2
6,http://localhost:8080/tienda1/publico/caracter...,http,localhost,8080.0,/tienda1/publico/caracteristicas.jsp,
7,http://localhost:8080/tienda1/publico/carrito.jsp,http,localhost,8080.0,/tienda1/publico/carrito.jsp,
8,http://localhost:8080/tienda1/publico/entrar.j...,http,localhost,8080.0,/tienda1/publico/entrar.jsp,errorMsg=Credenciales+incorrectas
9,http://localhost:8080/tienda1/publico/entrar.jsp,http,localhost,8080.0,/tienda1/publico/entrar.jsp,

In [55]:
print(repr(df["url"].iloc[0]))
print(repr(df["url"].iloc[1]))
print(
    df["url"].astype(str)
    .str.contains("HTTP/", regex=False)
    .sum()
)

'http://localhost:8080/tienda1/index.jsp'
'http://localhost:8080/tienda1/publico/anadir.jsp?id=3&nombre=Vino+Rioja&precio=100&cantidad=55&B1=A%F1adir+al+carrito'
0

In [56]:
def get_parameter_count(query):
    try:
        return len(parse_qs(str(query)))
    except:
        return 0

df["parameter_count"] = df["query"].apply(get_parameter_count)

In [57]:
print(df["parameter_count"].describe())

count    61065.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: parameter_count, dtype: float64

In [59]:
df["url_length"] = df["url"].astype(str).str.len()

In [60]:
print(df["url_length"].describe())

count    61065.000000
mean        81.325358
std         75.547066
min         22.000000
25%         48.000000
50%         50.000000
75%         68.000000
max        886.000000
Name: url_length, dtype: float64

In [61]:
df["path_length"] = df["path"].astype(str).str.len()

In [62]:
df["query_length"] = df["query"].astype(str).str.len()

In [63]:
from urllib.parse import unquote

df["url_decoded"] = (
    df["url_raw"]
    .astype(str)
    .apply(unquote)
)

In [64]:
display(
    df[
        ["url_raw", "url_decoded"]
    ].head(10)
)

,url_raw,url_decoded
0,http://localhost:8080/tienda1/index.jsp,http://localhost:8080/tienda1/index.jsp
1,http://localhost:8080/tienda1/publico/anadir.j...,http://localhost:8080/tienda1/publico/anadir.j...
2,http://localhost:8080/tienda1/publico/anadir.jsp,http://localhost:8080/tienda1/publico/anadir.jsp
3,http://localhost:8080/tienda1/publico/autentic...,http://localhost:8080/tienda1/publico/autentic...
4,http://localhost:8080/tienda1/publico/autentic...,http://localhost:8080/tienda1/publico/autentic...
5,http://localhost:8080/tienda1/publico/caracter...,http://localhost:8080/tienda1/publico/caracter...
6,http://localhost:8080/tienda1/publico/caracter...,http://localhost:8080/tienda1/publico/caracter...
7,http://localhost:8080/tienda1/publico/carrito.jsp,http://localhost:8080/tienda1/publico/carrito.jsp
8,http://localhost:8080/tienda1/publico/entrar.j...,http://localhost:8080/tienda1/publico/entrar.j...
9,http://localhost:8080/tienda1/publico/entrar.jsp,http://localhost:8080/tienda1/publico/entrar.jsp

In [65]:
df["query_decoded"] = (
    df["query"]
    .fillna("")
    .astype(str)
    .apply(unquote)
)

In [66]:
special_chars = r"""'"><;"""

In [67]:
df["special_char_count"] = (
    df["url_decoded"]
    .astype(str)
    .apply(lambda x: sum(char in special_chars for char in x))
)

In [68]:
print(df["special_char_count"].describe())

count    61065.000000
mean         0.168329
std          1.059654
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         15.000000
Name: special_char_count, dtype: float64

In [69]:
df["encoding_count"] = (
    df["url_raw"]
    .astype(str)
    .str.count("%")
)

In [70]:
df["path_depth"] = (
    df["path"]
    .astype(str)
    .str.strip("/")
    .str.count("/")
    + 1
)

In [73]:
display(
    df[
        [
            "url_raw",
            "url_decoded",
            "scheme",
            "url_host",
            "port",
            "path",
            "query",
            "parameter_count",
            "url_length",
            "path_length",
            "query_length"
        ]
    ].head(10)
)

,url_raw,url_decoded,scheme,url_host,port,path,query,parameter_count,url_length,path_length,query_length
0,http://localhost:8080/tienda1/index.jsp,http://localhost:8080/tienda1/index.jsp,http,localhost,8080.0,/tienda1/index.jsp,,0,39,18,0
1,http://localhost:8080/tienda1/publico/anadir.j...,http://localhost:8080/tienda1/publico/anadir.j...,http,localhost,8080.0,/tienda1/publico/anadir.jsp,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,117,27,68
2,http://localhost:8080/tienda1/publico/anadir.jsp,http://localhost:8080/tienda1/publico/anadir.jsp,http,localhost,8080.0,/tienda1/publico/anadir.jsp,,0,48,27,0
3,http://localhost:8080/tienda1/publico/autentic...,http://localhost:8080/tienda1/publico/autentic...,http,localhost,8080.0,/tienda1/publico/autenticar.jsp,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,116,31,63
4,http://localhost:8080/tienda1/publico/autentic...,http://localhost:8080/tienda1/publico/autentic...,http,localhost,8080.0,/tienda1/publico/autenticar.jsp,,0,52,31,0
5,http://localhost:8080/tienda1/publico/caracter...,http://localhost:8080/tienda1/publico/caracter...,http,localhost,8080.0,/tienda1/publico/caracteristicas.jsp,id=2,0,62,36,4
6,http://localhost:8080/tienda1/publico/caracter...,http://localhost:8080/tienda1/publico/caracter...,http,localhost,8080.0,/tienda1/publico/caracteristicas.jsp,,0,57,36,0
7,http://localhost:8080/tienda1/publico/carrito.jsp,http://localhost:8080/tienda1/publico/carrito.jsp,http,localhost,8080.0,/tienda1/publico/carrito.jsp,,0,49,28,0
8,http://localhost:8080/tienda1/publico/entrar.j...,http://localhost:8080/tienda1/publico/entrar.j...,http,localhost,8080.0,/tienda1/publico/entrar.jsp,errorMsg=Credenciales+incorrectas,0,82,27,33
9,http://localhost:8080/tienda1/publico/entrar.jsp,http://localhost:8080/tienda1/publico/entrar.jsp,http,localhost,8080.0,/tienda1/publico/entrar.jsp,,0,48,27,0

In [74]:
from urllib.parse import parse_qs

In [75]:
def count_parameters(query):
    if pd.isna(query) or str(query).strip() == "":
        return 0
    
    return len(parse_qs(str(query), keep_blank_values=True))

In [76]:
df["parameter_count"] = df["query"].apply(count_parameters)

In [77]:
display(
    df[
        ["query", "parameter_count"]
    ].head(10)
)

                                               query  parameter_count
0                                                                   0
1  id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...                5
2                                                                   0
3  modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...                5
4                                                                   0
5                                               id=2                1
6                                                                   0
7                                                                   0
8                  errorMsg=Credenciales+incorrectas                1
9                                                                   0